# Generated by Django 4.2.4 on 2023-10-23 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entrycomment",
            old_name="timestamp",
            new_name="created_at",
        ),
    ]
