# Generated by Django 4.2.4 on 2023-08-29 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_rename_auction_listing_comment_listing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="listings",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="listing",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.auctionlisting",
            ),
        ),
    ]
