# Generated by Django 4.2.4 on 2023-08-29 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_remove_watchlist_listings_watchlist_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="auction_listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bids",
                to="auctions.auctionlisting",
            ),
        ),
    ]
