# Generated by Django 4.2.4 on 2023-08-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_alter_bid_auction_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
