# Generated by Django 4.2.4 on 2023-08-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_auctionlisting_category_watchlist_comment_bid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="current_bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
