# This file contains the dictionaries for all musical keys and chords + their corresponding notes.

key_notes = {
    "Cb": ["Cb", "Db", "Eb", "Fb", "Gb", "Ab", "Bb"],
    "Cbm": ["Cb", "Db", "Ebb", "Fb", "Gb", "Abb", "Bbb"],
    "C": ["C", "D", "E", "F", "G", "A", "B"],
    "Cm": ["C", "D", "D#", "F", "G", "G#", "A#"],
    "C#": ["C#", "D#", "E", "F#", "G#", "A", "B"],
    "C#m": ["C#", "D#", "E", "F#", "G#", "A", "B"],
    "Db": ["Db", "Eb", "F", "Gb", "Ab", "Bb", "C"],
    "Dbm": ["Db", "Eb", "E", "Gb", "Ab", "A", "B"],
    "D": ["D", "E", "F#", "G", "A", "B", "C#"],
    "Dm": ["D", "E", "F", "G", "A", "A#", "C"],
    "D#": ["D#", "E#", "F##", "G#", "A#", "B#", "C##"],
    "D#m": ["D#", "E#", "F#", "G#", "A#", "B", "C#"],
    "Eb": ["Eb", "F", "G", "Ab", "Bb", "C", "D"],
    "Ebm": ["Eb", "F", "Gb", "Ab", "Bb", "Cb", "Db"],
    "E": ["E", "F#", "G#", "A", "B", "C#", "D#"],
    "Em": ["E", "F#", "G", "A", "B", "C", "D"],
    "F": ["F", "G", "A", "A#", "C", "D", "E"],
    "Fm": ["F", "G", "G#", "A#", "C", "C#", "D#"],
    "F#": ["F#", "G#", "A#", "B", "C#", "D#", "E#"],
    "F#m": ["F#", "G#", "A", "B", "C#", "D", "E"],
    "Gb": ["Gb", "Ab", "Bb", "Cb", "Db", "Eb", "F"],
    "Gbm": ["Gb", "Ab", "Bbb", "Cb", "Db", "Ebb", "Fb"],
    "G": ["G", "A", "B", "C", "D", "E", "F#"],
    "Gm": ["G", "A", "A#", "C", "D", "D#", "F"],
    "G#": ["G#", "A#", "B#", "C#", "D#", "E#", "F##"],
    "G#m": ["G#", "A#", "B", "C#", "D#", "E", "F#"],
    "Ab": ["Ab", "Bb", "C", "Db", "Eb", "F", "G"],
    "Abm": ["Ab", "Bb", "Cb", "Db", "Eb", "Fb", "Gb"],
    "A": ["A", "B", "C#", "D", "E", "F#", "G#"],
    "Am": ["A", "B", "C", "D", "E", "F", "G"],
    "A#": ["A#", "B#", "C##", "D#", "E#", "F##", "G##"],
    "A#m": ["A#", "B#", "C#", "D#", "E#", "F#", "G#"],
    "Bb": ["Bb", "C", "D", "Eb", "F", "G", "A"],
    "Bbm": ["Bb", "C", "Db", "Eb", "F", "Gb", "Ab"],
    "B": ["B", "C#", "D#", "E", "F#", "G#", "A#"],
    "Bm": ["B", "C#", "D", "E", "F#", "G", "A"],
}

chord_notes = {
    "C": ["C", "E", "G"],
    "Cm": ["C", "D#", "G"],
    "Cdim": ["C", "D#", "F#"],
    "Caug": ["C", "E", "G#"],
    "Cmaj7": ["C", "E", "G", "B"],
    "C7": ["C", "E", "G", "Bb"],
    "Cm7": ["C", "D#", "G", "A#"],
    "Cmaj9": ["C", "E", "G", "B", "D"],
    "C9": ["C", "E", "G", "Bb", "D"],
    "Cm9": ["C", "D#", "G", "A#", "D"],
    "Cmaj11": ["C", "E", "G", "B", "D", "F"],
    "C11": ["C", "E", "G", "Bb", "D", "F"],
    "Cm11": ["C", "D#", "G", "A#", "D", "F"],
    "Cmaj13": ["C", "E", "G", "B", "D", "F", "A"],
    "C13": ["C", "E", "G", "Bb", "D", "F", "A"],
    "Cm13": ["C", "D#", "G", "A#", "D", "F", "A"],
    "Cmaj6": ["C", "E", "G", "A"],
    "C6": ["C", "E", "G", "A"],
    "Cm6": ["C", "D#", "G", "A"],
    "Cadd9": ["C", "E", "G", "D"],
    "Cadd11": ["C", "E", "G", "F"],
    "Cadd13": ["C", "E", "G", "A"],
    "Cmadd9": ["C", "D#", "G", "D"],
    "Cmadd11": ["C", "D#", "G", "F"],
    "Cmadd13": ["C", "D#", "G", "A"],
    "C6/9": ["C", "E", "G", "A", "D"],
    "Cmaj7b5": ["C", "E", "G#"],
    "Cmaj7#5": ["C", "E", "G#"],
    "Cm7b5": ["C", "D#", "F#"],
    "CmMaj7": ["C", "D#", "G", "B"],
    "C7b5": ["C", "E", "F#"],
    "C7#5": ["C", "E", "G#"],
    "C7sus4": ["C", "F", "G", "Bb"],
    "C9b5": ["C", "E", "F#", "Bb", "D"],
    "C9#5": ["C", "E", "G#", "Bb", "D"],
    "C9sus4": ["C", "F", "G", "Bb", "D"],
    "C13b5": ["C", "E", "F#", "Bb", "D", "A"],
    "C13#5": ["C", "E", "G#", "Bb", "D", "A"],
    "Csus2": ["C", "D", "G"],
    "Csus4": ["C", "F", "G"],
    "C7sus2": ["C", "D", "G", "Bb"],
    "C7sus4": ["C", "F", "G", "Bb"],
    "Cm7sus2": ["C", "D#", "G", "A#"],
    "Cm7sus4": ["C", "F", "G", "A#"],
    "Cmaj7sus2": ["C", "D", "G", "B"],
    "Cmaj7sus4": ["C", "F", "G", "B"],
    "Cadd9/D": ["D", "E", "G", "C"],
    "Cadd9/E": ["E", "G", "C"],
    "Cadd9/F": ["F", "G", "C"],
    "Cadd9/G": ["G", "C", "E"],
    "Cadd9/A": ["A", "C", "E", "G"],
    "Cadd9/B": ["B", "C", "E", "G"],
    "Cmaj7/D": ["D", "E", "G", "B", "C"],
    "Cmaj7/E": ["E", "G", "B", "C"],
    "Cmaj7/F": ["F", "G", "B", "C"],
    "Cmaj7/G": ["G", "C", "E", "B"],
    "Cmaj7/A": ["A", "C", "E", "G", "B"],
    "Cmaj7/B": ["B", "C", "E", "G", "B"],
    "C7/D": ["D", "E", "G", "Bb", "C"],
    "C7/E": ["E", "G", "Bb", "C"],
    "C7/F": ["F", "G", "Bb", "C"],
    "C7/G": ["G", "Bb", "C", "E"],
    "C7/A": ["A", "C", "E", "G", "Bb"],
    "C7/B": ["B", "C", "E", "G", "Bb"],
    "Cm7/D": ["D", "D#", "G", "A#", "C"],
    "Cm7/E": ["E", "G", "A#", "C"],
    "Cm7/F": ["F", "G", "A#", "C"],
    "Cm7/G": ["G", "A#", "C", "D#"],
    "Cm7/A": ["A", "A#", "C", "D#", "G"],
    "Cm7/B": ["B", "C", "D#", "G", "A#"],
    "Cmaj9/D": ["D", "E", "G", "B", "C"],
    "Cmaj9/E": ["E", "G", "B", "C"],
    "Cmaj9/F": ["F", "G", "B", "C"],
    "Cmaj9/G": ["G", "C", "E", "B", "D"],
    "Cmaj9/A": ["A", "C", "E", "G", "B", "D"],
    "Cmaj9/B": ["B", "C", "E", "G", "B", "D"],
    "C9/D": ["D", "E", "G", "Bb", "C"],
    "C9/E": ["E", "G", "Bb", "C"],
    "C9/F": ["F", "G", "Bb", "C"],
    "C9/G": ["G", "Bb", "C", "E", "D"],
    "C9/A": ["A", "C", "E", "G", "Bb", "D"],
    "C9/B": ["B", "C", "E", "G", "Bb", "D"],
    "Cm9/D": ["D", "D#", "G", "A#", "C"],
    "Cm9/E": ["E", "G", "A#", "C"],
    "Cm9/F": ["F", "G", "A#", "C"],
    "Cm9/G": ["G", "A#", "C", "D#", "D"],
    "Cm9/A": ["A", "A#", "C", "D#", "G"],
    "Cm9/B": ["B", "C", "D#", "G", "A#"],
    "C#": ["C#", "E#", "G#"],
    "C#m": ["C#", "E", "G#"],
    "C#dim": ["C#", "E", "G"],
    "C#aug": ["C#", "E#", "Gx"],
    "C#maj7": ["C#", "E#", "G#", "B#"],
    "C#7": ["C#", "E#", "G#", "B"],
    "C#m7": ["C#", "E", "G#", "B"],
    "C#maj9": ["C#", "E#", "G#", "B#", "D#"],
    "C#9": ["C#", "E#", "G#", "B", "D#"],
    "C#m9": ["C#", "E", "G#", "B", "D#"],
    "C#maj11": ["C#", "E#", "G#", "B#", "D#", "F#"],
    "C#11": ["C#", "E#", "G#", "B", "D#", "F#"],
    "C#m11": ["C#", "E", "G#", "B", "D#", "F#"],
    "C#maj13": ["C#", "E#", "G#", "B#", "D#", "F#", "A#"],
    "C#13": ["C#", "E#", "G#", "B", "D#", "F#", "A#"],
    "C#m13": ["C#", "E", "G#", "B", "D#", "F#", "A#"],
    "C#maj6": ["C#", "E#", "G#", "A#"],
    "C#6": ["C#", "E#", "G#", "A#"],
    "C#m6": ["C#", "E", "G#", "A#"],
    "C#add9": ["C#", "E#", "G#", "D#"],
    "C#add11": ["C#", "E#", "G#", "F#"],
    "C#add13": ["C#", "E#", "G#", "A#"],
    "C#madd9": ["C#", "E", "G#", "D#"],
    "C#madd11": ["C#", "E", "G#", "F#"],
    "C#madd13": ["C#", "E", "G#", "A#"],
    "C#6/9": ["C#", "E#", "G#", "A#", "D#"],
    "C#maj7b5": ["C#", "E#", "Gx"],
    "C#maj7#5": ["C#", "E#", "Gx"],
    "C#m7b5": ["C#", "E", "G"],
    "C#mMaj7": ["C#", "E", "G#", "B#"],
    "C#7b5": ["C#", "E#", "G"],
    "C#7#5": ["C#", "E#", "Gx"],
    "C#7sus4": ["C#", "F#", "G#", "B"],
    "C#9b5": ["C#", "E#", "G", "B", "D#"],
    "C#9#5": ["C#", "E#", "Gx", "B", "D#"],
    "C#9sus4": ["C#", "F#", "G#", "B", "D#"],
    "C#13b5": ["C#", "E#", "G", "B", "D#", "A#"],
    "C#13#5": ["C#", "E#", "Gx", "B", "D#", "A#"],
    "C#sus2": ["C#", "D#", "G#"],
    "C#sus4": ["C#", "F#", "G#"],
    "C#7sus2": ["C#", "D#", "G#", "B"],
    "C#7sus4": ["C#", "F#", "G#", "B"],
    "C#m7sus2": ["C#", "E", "G#", "B"],
    "C#m7sus4": ["C#", "F#", "G#", "B"],
    "C#maj7sus2": ["C#", "D#", "G#", "B#"],
    "C#maj7sus4": ["C#", "F#", "G#", "B#"],
    "C#add9/D#": ["D#", "E#", "G#", "C#"],
    "C#add9/E": ["E", "G#", "C#"],
    "C#add9/F#": ["F#", "G#", "C#"],
    "C#add9/G#": ["G#", "C#", "E#", "B#"],
    "C#add9/A#": ["A#", "C#", "E#", "G#", "B#"],
    "C#add9/B": ["B", "C#", "E#", "G#", "B#"],
    "C#maj7/D#": ["D#", "E#", "G#", "B#", "C#"],
    "C#maj7/E": ["E", "G#", "B#", "C#"],
    "C#maj7/F#": ["F#", "G#", "B#", "C#"],
    "C#maj7/G#": ["G#", "C#", "E#", "B#", "D#"],
    "C#maj7/A#": ["A#", "C#", "E#", "G#", "B#", "D#"],
    "C#maj7/B": ["B", "C#", "E#", "G#", "B#", "D#"],
    "C#7/D#": ["D#", "E#", "G#", "B", "C#"],
    "C#7/E": ["E", "G#", "B", "C#"],
    "C#7/F#": ["F#", "G#", "B", "C#"],
    "C#7/G#": ["G#", "B", "C#", "E#", "D#"],
    "C#7/A#": ["A#", "C#", "E#", "G#", "B", "D#"],
    "C#7/B": ["B", "C#", "E#", "G#", "B", "D#"],
    "C#m7/D#": ["D#", "E", "G#", "B", "C#"],
    "C#m7/E": ["E", "G#", "B", "C#"],
    "C#m7/F#": ["F#", "G#", "B", "C#"],
    "C#m7/G#": ["G#", "A#", "C#", "E", "B"],
    "C#m7/A#": ["A#", "B", "C#", "E", "G#", "C#"],
    "C#m7/B": ["B", "C#", "E", "G#", "B"],
    "C#maj9/D#": ["D#", "E#", "G#", "B#", "C#"],
    "C#maj9/E": ["E", "G#", "B#", "C#"],
    "C#maj9/F#": ["F#", "G#", "B#", "C#"],
    "C#maj9/G#": ["G#", "C#", "E#", "B#", "D#", "F#"],
    "C#maj9/A#": ["A#", "C#", "E#", "G#", "B#", "D#", "F#"],
    "C#maj9/B": ["B", "C#", "E#", "G#", "B#", "D#", "F#"],
    "C#9/D#": ["D#", "E#", "G#", "B", "C#"],
    "C#9/E": ["E", "G#", "B", "C#"],
    "C#9/F#": ["F#", "G#", "B", "C#"],
    "C#9/G#": ["G#", "B", "C#", "E#", "D#", "F#"],
    "C#9/A#": ["A#", "C#", "E#", "G#", "B", "D#", "F#"],
    "C#9/B": ["B", "C#", "E#", "G#", "B", "D#", "F#"],
    "C#m9/D#": ["D#", "E", "G#", "B", "C#"],
    "C#m9/E": ["E", "G#", "B", "C#"],
    "C#m9/F#": ["F#", "G#", "B", "C#"],
    "C#m9/G#": ["G#", "A#", "C#", "E", "B"],
    "C#m9/A#": ["A#", "B", "C#", "E", "G#", "C#"],
    "C#m9/B": ["B", "C#", "E", "G#", "B", "D#", "F#"],
    "Db": ["Db", "F", "Ab"],
    "Dbm": ["Db", "E", "Ab"],
    "Dbdim": ["Db", "E", "G"],
    "Dbaug": ["Db", "F", "A"],
    "Dbmaj7": ["Db", "F", "Ab", "C"],
    "Db7": ["Db", "F", "Ab", "Cb"],
    "Dbm7": ["Db", "E", "Ab", "Cb"],
    "Dbmaj9": ["Db", "F", "Ab", "C", "Eb"],
    "Db9": ["Db", "F", "Ab", "Cb", "Eb"],
    "Dbm9": ["Db", "E", "Ab", "Cb", "Eb"],
    "Dbmaj11": ["Db", "F", "Ab", "C", "Eb", "Gb"],
    "Db11": ["Db", "F", "Ab", "Cb", "Eb", "Gb"],
    "Dbm11": ["Db", "E", "Ab", "Cb", "Eb", "Gb"],
    "Dbmaj13": ["Db", "F", "Ab", "C", "Eb", "Gb", "Bb"],
    "Db13": ["Db", "F", "Ab", "Cb", "Eb", "Gb", "Bb"],
    "Dbm13": ["Db", "E", "Ab", "Cb", "Eb", "Gb", "Bb"],
    "Dbmaj6": ["Db", "F", "Ab", "Bb"],
    "Db6": ["Db", "F", "Ab", "Bb"],
    "Dbm6": ["Db", "E", "Ab", "Bb"],
    "Dbadd9": ["Db", "F", "Ab", "Eb"],
    "Dbadd11": ["Db", "F", "Ab", "Bb"],
    "Dbadd13": ["Db", "F", "Ab", "C"],
    "Dbmadd9": ["Db", "E", "Ab", "Eb"],
    "Dbmadd11": ["Db", "E", "Ab", "Bb"],
    "Dbmadd13": ["Db", "E", "Ab", "C"],
    "Db6/9": ["Db", "F", "Ab", "Bb", "Eb"],
    "Dbmaj7b5": ["Db", "F", "A"],
    "Dbmaj7#5": ["Db", "F", "A"],
    "Dbm7b5": ["Db", "E", "G"],
    "DbmMaj7": ["Db", "E", "Ab", "C"],
    "Db7b5": ["Db", "F", "G"],
    "Db7#5": ["Db", "F", "A"],
    "Db7sus4": ["Db", "G", "Ab", "Cb"],
    "Db9b5": ["Db", "F", "G", "Cb", "Eb"],
    "Db9#5": ["Db", "F", "A", "Cb", "Eb"],
    "Db9sus4": ["Db", "G", "Ab", "Cb", "Eb"],
    "Db13b5": ["Db", "F", "G", "Cb", "Eb", "Bb"],
    "Db13#5": ["Db", "F", "A", "Cb", "Eb", "Bb"],
    "Dbsus2": ["Db", "E", "Ab"],
    "Dbsus4": ["Db", "G", "Ab"],
    "Db7sus2": ["Db", "E", "Ab", "Cb"],
    "Db7sus4": ["Db", "G", "Ab", "Cb"],
    "Dbm7sus2": ["Db", "E", "Ab", "Cb"],
    "Dbm7sus4": ["Db", "G", "Ab", "Cb"],
    "Dbmaj7sus2": ["Db", "E", "Ab", "C"],
    "Dbmaj7sus4": ["Db", "G", "Ab", "C"],
    "Dbadd9/F": ["Db", "F", "Ab"],
    "Dbadd9/Gb": ["Db", "E", "Ab"],
    "Dbadd9/Ab": ["Ab", "Db", "F"],
    "Dbadd9/E": ["Db", "E", "Ab", "Bb"],
    "Dbadd9/Gb": ["Db", "E", "Ab"],
    "Dbmaj7/F": ["Db", "F", "Ab", "C"],
    "Dbmaj7/Gb": ["Db", "E", "Ab", "C"],
    "Dbmaj7/Ab": ["Ab", "Db", "F", "C"],
    "Dbmaj7/E": ["Db", "E", "Ab", "C"],
    "Dbmaj7/Gb": ["Db", "E", "Ab", "C"],
    "Db7/F": ["Db", "F", "Ab", "Cb"],
    "Db7/Gb": ["Db", "E", "Ab", "Cb"],
    "Db7/Ab": ["Ab", "Db", "F", "Cb"],
    "Db7/E": ["Db", "E", "Ab", "Cb"],
    "Db7/Gb": ["Db", "E", "Ab", "Cb"],
    "Dbm7/F": ["Db", "F", "Ab", "Cb"],
    "Dbm7/Gb": ["Db", "E", "Ab", "Cb"],
    "Dbm7/Ab": ["Ab", "Db", "F", "Cb"],
    "Dbm7/E": ["Db", "E", "Ab", "Cb"],
    "Dbm7/Gb": ["Db", "E", "Ab", "Cb"],
    "Dbmaj9/F": ["Db", "F", "Ab", "C", "Eb"],
    "Dbmaj9/Gb": ["Db", "E", "Ab", "C", "Eb"],
    "Dbmaj9/Ab": ["Ab", "Db", "F", "C", "Eb"],
    "Dbmaj9/E": ["Db", "E", "Ab", "C", "Eb"],
    "Dbmaj9/Gb": ["Db", "E", "Ab", "C", "Eb"],
    "Db9/F": ["Db", "F", "Ab", "Cb", "Eb"],
    "Db9/Gb": ["Db", "E", "Ab", "Cb", "Eb"],
    "Db9/Ab": ["Ab", "Db", "F", "Cb", "Eb"],
    "Db9/E": ["Db", "E", "Ab", "Cb", "Eb"],
    "Db9/Gb": ["Db", "E", "Ab", "Cb", "Eb"],
    "Dbm9/F": ["Db", "F", "Ab", "Cb", "Eb"],
    "Dbm9/Gb": ["Db", "E", "Ab", "Cb", "Eb"],
    "Dbm9/Ab": ["Ab", "Db", "F", "Cb", "Eb"],
    "Dbm9/E": ["Db", "E", "Ab", "Cb", "Eb"],
    "D": ["D", "F#", "A"],
    "Dm": ["D", "F", "A"],
    "Ddim": ["D", "F", "Ab"],
    "Daug": ["D", "F#", "A#"],
    "Dmaj7": ["D", "F#", "A", "C#"],
    "D7": ["D", "F#", "A", "C"],
    "Dm7": ["D", "F", "A", "C"],
    "Dmaj9": ["D", "F#", "A", "C#", "E"],
    "D9": ["D", "F#", "A", "C", "E"],
    "Dm9": ["D", "F", "A", "C", "E"],
    "Dmaj11": ["D", "F#", "A", "C#", "E", "G"],
    "D11": ["D", "F#", "A", "C", "E", "G"],
    "Dm11": ["D", "F", "A", "C", "E", "G"],
    "Dmaj13": ["D", "F#", "A", "C#", "E", "G", "B"],
    "D13": ["D", "F#", "A", "C", "E", "G", "B"],
    "Dm13": ["D", "F", "A", "C", "E", "G", "B"],
    "Dmaj6": ["D", "F#", "A", "B"],
    "D6": ["D", "F#", "A", "B"],
    "Dm6": ["D", "F", "A", "B"],
    "Dadd9": ["D", "F#", "A", "E"],
    "Dadd11": ["D", "F#", "A", "G"],
    "Dadd13": ["D", "F#", "A", "B"],
    "Dmadd9": ["D", "F", "A", "E"],
    "Dmadd11": ["D", "F", "A", "G"],
    "Dmadd13": ["D", "F", "A", "B"],
    "D6/9": ["D", "F#", "A", "B", "E"],
    "Dmaj7b5": ["D", "F#", "A#"],
    "Dmaj7#5": ["D", "F#", "Bb"],
    "Dm7b5": ["D", "F", "Ab"],
    "DmMaj7": ["D", "F", "A", "C#"],
    "D7b5": ["D", "F#", "Ab"],
    "D7#5": ["D", "F#", "A#"],
    "D7sus4": ["D", "G", "A", "C"],
    "D9b5": ["D", "F#", "Ab", "C", "E"],
    "D9#5": ["D", "F#", "A#", "C", "E"],
    "D9sus4": ["D", "G", "A", "C", "E"],
    "D13b5": ["D", "F#", "Ab", "C", "E", "B"],
    "D13#5": ["D", "F#", "A#", "C", "E", "B"],
    "Dsus2": ["D", "E", "A"],
    "Dsus4": ["D", "G", "A"],
    "D7sus2": ["D", "E", "A", "C"],
    "D7sus4": ["D", "G", "A", "C"],
    "Dm7sus2": ["D", "F", "A", "C"],
    "Dm7sus4": ["D", "G", "A", "C"],
    "Dmaj7sus2": ["D", "E", "A", "C#"],
    "Dmaj7sus4": ["D", "G", "A", "C#"],
    "Dadd9/C": ["C", "D", "F#", "A", "E"],
    "Dadd9/E": ["E", "A", "D", "F#", "B"],
    "Dadd9/F": ["F", "A", "D", "F#", "B"],
    "Dadd9/G": ["G", "A", "D", "F#", "B"],
    "Dadd9/A": ["A", "D", "F#", "B"],
    "Dadd9/B": ["B", "D", "F#", "A", "E"],
    "Dmaj7/C": ["C", "D", "F#", "A", "C#"],
    "Dmaj7/E": ["E", "A", "D", "F#", "C#"],
    "Dmaj7/F": ["F", "A", "D", "F#", "C#"],
    "Dmaj7/G": ["G", "A", "D", "F#", "C#"],
    "Dmaj7/A": ["A", "D", "F#", "C#"],
    "Dmaj7/B": ["B", "D", "F#", "A", "C#"],
    "D7/C": ["C", "D", "F#", "A", "C"],
    "D7/E": ["E", "A", "D", "F#", "C"],
    "D7/F": ["F", "A", "D", "F#", "C"],
    "D7/G": ["G", "A", "D", "F#", "C"],
    "D7/A": ["A", "D", "F#", "C"],
    "D7/B": ["B", "D", "F#", "A", "C"],
    "Dm7/C": ["C", "D", "F", "A", "C"],
    "Dm7/E": ["E", "A", "D", "F", "C"],
    "Dm7/F": ["F", "A", "D", "F", "C"],
    "Dm7/G": ["G", "A", "D", "F", "C"],
    "Dm7/A": ["A", "D", "F", "C"],
    "Dm7/B": ["B", "D", "F", "A", "C"],
    "Dmaj9/C": ["C", "D", "F#", "A", "C#", "E"],
    "Dmaj9/E": ["E", "A", "D", "F#", "C#", "B"],
    "Dmaj9/F": ["F", "A", "D", "F#", "C#", "B"],
    "Dmaj9/G": ["G", "A", "D", "F#", "C#", "B"],
    "Dmaj9/A": ["A", "D", "F#", "C#", "E"],
    "Dmaj9/B": ["B", "D", "F#", "A", "C#", "E"],
    "D9/C": ["C", "D", "F#", "A", "C", "E"],
    "D9/E": ["E", "A", "D", "F#", "C", "B"],
    "D9/F": ["F", "A", "D", "F#", "C", "B"],
    "D9/G": ["G", "A", "D", "F#", "C", "B"],
    "D9/A": ["A", "D", "F#", "C", "E"],
    "D9/B": ["B", "D", "F#", "A", "C", "E"],
    "Dm9/C": ["C", "D", "F", "A", "C", "E"],
    "Dm9/E": ["E", "A", "D", "F", "C", "B"],
    "Dm9/F": ["F", "A", "D", "F", "C", "B"],
    "Dm9/G": ["G", "A", "D", "F", "C", "B"],
    "Dm9/A": ["A", "D", "F", "C", "E"],
    "Dm9/B": ["B", "D", "F", "A", "C", "E"],
    "D#": ["D#", "F##", "A#"],
    "D#m": ["D#", "F#", "A#"],
    "D#dim": ["D#", "F#", "A"],
    "D#aug": ["D#", "F##", "B"],
    "D#maj7": ["D#", "F##", "A#", "C##"],
    "D#7": ["D#", "F##", "A#", "C#"],
    "D#m7": ["D#", "F#", "A#", "C#"],
    "D#maj9": ["D#", "F##", "A#", "C##", "E#"],
    "D#9": ["D#", "F##", "A#", "C#", "E#"],
    "D#m9": ["D#", "F#", "A#", "C#", "E#"],
    "D#maj11": ["D#", "F##", "A#", "C##", "E#", "G#"],
    "D#11": ["D#", "F##", "A#", "C#", "E#", "G#"],
    "D#m11": ["D#", "F#", "A#", "C#", "E#", "G#"],
    "D#maj13": ["D#", "F##", "A#", "C##", "E#", "G#", "B#"],
    "D#13": ["D#", "F##", "A#", "C#", "E#", "G#", "B#"],
    "D#m13": ["D#", "F#", "A#", "C#", "E#", "G#", "B#"],
    "D#maj6": ["D#", "F##", "A#", "B#"],
    "D#6": ["D#", "F##", "A#", "B#"],
    "D#m6": ["D#", "F#", "A#", "B#"],
    "D#add9": ["D#", "F##", "A#", "E#"],
    "D#add11": ["D#", "F##", "A#", "G#"],
    "D#add13": ["D#", "F##", "A#", "C##"],
    "D#madd9": ["D#", "F#", "A#", "E#"],
    "D#madd11": ["D#", "F#", "A#", "G#"],
    "D#madd13": ["D#", "F#", "A#", "C##"],
    "D#6/9": ["D#", "F##", "A#", "B#", "E#"],
    "D#maj7b5": ["D#", "F##", "B"],
    "D#maj7#5": ["D#", "F###", "B"],
    "D#m7b5": ["D#", "F#", "A"],
    "D#mMaj7": ["D#", "F#", "A#", "C##"],
    "D#7b5": ["D#", "F##", "A"],
    "D#7#5": ["D#", "F###", "A"],
    "D#7sus4": ["D#", "G#", "A#", "C#"],
    "D#9b5": ["D#", "F##", "A", "C#", "E#"],
    "D#9#5": ["D#", "F###", "A#", "C#", "E#"],
    "D#9sus4": ["D#", "G#", "A#", "C#", "E#"],
    "D#13b5": ["D#", "F##", "A", "C#", "E#", "B#"],
    "D#13#5": ["D#", "F###", "A#", "C#", "E#", "B#"],
    "D#sus2": ["D#", "E#", "A#"],
    "D#sus4": ["D#", "G#", "A#"],
    "D#7sus2": ["D#", "E#", "A#", "C#"],
    "D#7sus4": ["D#", "G#", "A#", "C#"],
    "D#m7sus2": ["D#", "F#", "A#", "C#"],
    "D#m7sus4": ["D#", "G#", "A#", "C#"],
    "D#maj7sus2": ["D#", "E#", "A#", "C##"],
    "D#maj7sus4": ["D#", "G#", "A#", "C##"],
    "D#add9/F": ["F", "F##", "A#"],
    "D#add9/G": ["G", "A#", "D#", "F##"],
    "D#add9/A#": ["A#", "D#", "F##", "G#", "A#"],
    "D#add9/G": ["G", "A#", "D#", "F##"],
    "D#maj7/F": ["F", "F##", "A#", "C##"],
    "D#maj7/G": ["G", "A#", "C##", "D#", "F##"],
    "D#maj7/A#": ["A#", "D#", "F##", "A#", "C##"],
    "D#maj7/G": ["G", "A#", "C##", "D#", "F##"],
    "D#7/F": ["F", "F##", "A#", "C#"],
    "D#7/G": ["G", "A#", "C#", "D#", "F##"],
    "D#7/A#": ["A#", "D#", "F##", "G#", "C#"],
    "D#7/G": ["G", "A#", "C#", "D#", "F##"],
    "D#m7/F": ["F", "F#", "A#", "C#"],
    "D#m7/G": ["G", "A#", "C#", "D#", "F#"],
    "D#m7/A#": ["A#", "D#", "F#", "A#", "C#"],
    "D#m7/G": ["G", "A#", "C#", "D#", "F#"],
    "D#maj9/F": ["F", "F##", "A#", "C##", "E#"],
    "D#maj9/G": ["G", "A#", "C##", "D#", "F##", "G#"],
    "D#maj9/A#": ["A#", "D#", "F##", "A#", "C##", "E#"],
    "D#maj9/G": ["G", "A#", "C##", "D#", "F##", "G#"],
    "D#9/F": ["F", "F##", "A#", "C#", "E#"],
    "D#9/G": ["G", "A#", "C#", "D#", "F##", "G#"],
    "D#9/A#": ["A#", "D#", "F##", "A#", "C#", "E#"],
    "D#9/G": ["G", "A#", "C#", "D#", "F##", "G#"],
    "D#m9/F": ["F", "F#", "A#", "C#", "E#"],
    "D#m9/G": ["G", "A#", "C#", "D#", "F#", "A#"],
    "D#m9/A#": ["A#", "D#", "F#", "A#", "C#", "E#"],
    "D#m9/G": ["G", "A#", "C#", "D#", "F#", "A#"],
    "Eb": ["Eb", "G", "Bb"],
    "Ebm": ["Eb", "Gb", "Bb"],
    "Ebdim": ["Eb", "Gb", "A"],
    "Ebaug": ["Eb", "G", "B"],
    "Ebmaj7": ["Eb", "G", "Bb", "D"],
    "Eb7": ["Eb", "G", "Bb", "Db"],
    "Ebm7": ["Eb", "Gb", "Bb", "Db"],
    "Ebmaj9": ["Eb", "G", "Bb", "D", "F"],
    "Eb9": ["Eb", "G", "Bb", "Db", "F"],
    "Ebm9": ["Eb", "Gb", "Bb", "Db", "F"],
    "Ebmaj11": ["Eb", "G", "Bb", "D", "F", "A"],
    "Eb11": ["Eb", "G", "Bb", "Db", "F", "A"],
    "Ebm11": ["Eb", "Gb", "Bb", "Db", "F", "A"],
    "Ebmaj13": ["Eb", "G", "Bb", "D", "F", "A", "C"],
    "Eb13": ["Eb", "G", "Bb", "Db", "F", "A", "C"],
    "Ebm13": ["Eb", "Gb", "Bb", "Db", "F", "A", "C"],
    "Ebmaj6": ["Eb", "G", "Bb", "C"],
    "Eb6": ["Eb", "G", "Bb", "C"],
    "Ebm6": ["Eb", "Gb", "Bb", "C"],
    "Ebadd9": ["Eb", "G", "Bb", "F"],
    "Ebadd11": ["Eb", "G", "Bb", "C"],
    "Ebadd13": ["Eb", "G", "Bb", "D"],
    "Ebmadd9": ["Eb", "Gb", "Bb", "F"],
    "Ebmadd11": ["Eb", "Gb", "Bb", "C"],
    "Ebmadd13": ["Eb", "Gb", "Bb", "D"],
    "Eb6/9": ["Eb", "G", "Bb", "C", "F"],
    "Ebmaj7b5": ["Eb", "G", "B"],
    "Ebmaj7#5": ["Eb", "G", "B"],
    "Ebm7b5": ["Eb", "Gb", "A"],
    "EbmMaj7": ["Eb", "Gb", "Bb", "D"],
    "Eb7b5": ["Eb", "G", "A"],
    "Eb7#5": ["Eb", "G", "B"],
    "Eb7sus4": ["Eb", "Ab", "Bb", "Db"],
    "Eb9b5": ["Eb", "G", "A", "Db", "F"],
    "Eb9#5": ["Eb", "G", "B", "Db", "F"],
    "Eb9sus4": ["Eb", "Ab", "Bb", "Db", "F"],
    "Eb13b5": ["Eb", "G", "A", "Db", "F", "C"],
    "Eb13#5": ["Eb", "G", "B", "Db", "F", "C"],
    "Ebsus2": ["Eb", "F", "Bb"],
    "Ebsus4": ["Eb", "Ab", "Bb"],
    "Eb7sus2": ["Eb", "F", "Bb", "Db"],
    "Eb7sus4": ["Eb", "Ab", "Bb", "Db"],
    "Ebm7sus2": ["Eb", "Gb", "Bb", "Db"],
    "Ebm7sus4": ["Eb", "Ab", "Bb", "Db"],
    "Ebmaj7sus2": ["Eb", "F", "Bb", "D"],
    "Ebmaj7sus4": ["Eb", "Ab", "Bb", "D"],
    "Ebadd9/Ab": ["Ab", "Bb", "Eb", "G"],
    "Ebadd9/Db": ["Db", "Eb", "G"],
    "Ebadd9/E": ["Eb", "G", "Bb"],
    "Ebadd9/Ab": ["Ab", "Bb", "Eb", "G"],
    "Ebmaj7/Ab": ["Ab", "Bb", "Eb", "G", "D"],
    "Ebmaj7/Db": ["Db", "Eb", "G", "Bb", "D"],
    "Ebmaj7/E": ["Eb", "G", "Bb", "D"],
    "Ebmaj7/Ab": ["Ab", "Bb", "Eb", "G", "D"],
    "Eb7/Ab": ["Ab", "Bb", "Eb", "Db"],
    "Eb7/Db": ["Db", "Eb", "G", "Bb", "Db"],
    "Eb7/E": ["Eb", "G", "Bb", "Db"],
    "Eb7/Ab": ["Ab", "Bb", "Eb", "Db"],
    "Ebm7/Ab": ["Ab", "Bb", "Eb", "Db"],
    "Ebm7/Db": ["Db", "Eb", "G", "Bb", "Db"],
    "Ebm7/E": ["Eb", "G", "Bb", "Db"],
    "Ebm7/Ab": ["Ab", "Bb", "Eb", "Db"],
    "Ebmaj9/Ab": ["Ab", "Bb", "Eb", "G", "D"],
    "Ebmaj9/Db": ["Db", "Eb", "G", "Bb", "D"],
    "Ebmaj9/E": ["Eb", "G", "Bb", "D"],
    "Ebmaj9/Ab": ["Ab", "Bb", "Eb", "G", "D"],
    "Eb9/Ab": ["Ab", "Bb", "Eb", "Db", "F"],
    "Eb9/Db": ["Db", "Eb", "G", "Bb", "Db"],
    "Eb9/E": ["Eb", "G", "Bb", "Db", "F"],
    "Eb9/Ab": ["Ab", "Bb", "Eb", "Db", "F"],
    "Ebm9/Ab": ["Ab", "Bb", "Eb", "Db", "F"],
    "Ebm9/Db": ["Db", "Eb", "G", "Bb", "Db"],
    "Ebm9/E": ["Eb", "G", "Bb", "Db", "F"],
    "Ebm9/Ab": ["Ab", "Bb", "Eb", "Db", "F"],
    "E": ["E", "G#", "B"],
    "Em": ["E", "G", "B"],
    "Edim": ["E", "G", "Bb"],
    "Eaug": ["E", "G#", "B#"],
    "Emaj7": ["E", "G#", "B", "D#"],
    "E7": ["E", "G#", "B", "D"],
    "Em7": ["E", "G", "B", "D"],
    "Emaj9": ["E", "G#", "B", "D#", "F#"],
    "E9": ["E", "G#", "B", "D", "F#"],
    "Em9": ["E", "G", "B", "D", "F#"],
    "Emaj11": ["E", "G#", "B", "D#", "F#", "A"],
    "E11": ["E", "G#", "B", "D", "F#", "A"],
    "Em11": ["E", "G", "B", "D", "F#", "A"],
    "Emaj13": ["E", "G#", "B", "D#", "F#", "A", "C#"],
    "E13": ["E", "G#", "B", "D", "F#", "A", "C#"],
    "Em13": ["E", "G", "B", "D", "F#", "A", "C#"],
    "Emaj6": ["E", "G#", "B", "C#"],
    "E6": ["E", "G#", "B", "C#"],
    "Em6": ["E", "G", "B", "C#"],
    "Eadd9": ["E", "G#", "B", "F#"],
    "Eadd11": ["E", "G#", "B", "A"],
    "Eadd13": ["E", "G#", "B", "C#"],
    "Emadd9": ["E", "G", "B", "F#"],
    "Emadd11": ["E", "G", "B", "A"],
    "Emadd13": ["E", "G", "B", "C#"],
    "E6/9": ["E", "G#", "B", "C#", "F#"],
    "Emaj7b5": ["E", "G#", "Bb", "D#"],
    "Emaj7#5": ["E", "G#", "C", "D#"],
    "Em7b5": ["E", "G", "Bb", "D"],
    "EmMaj7": ["E", "G", "B", "D#"],
    "E7b5": ["E", "G#", "Bb", "D"],
    "E7#5": ["E", "G#", "C", "D"],
    "E7sus4": ["E", "A", "B", "D"],
    "E9b5": ["E", "G#", "Bb", "D", "F#"],
    "E9#5": ["E", "G#", "C", "D", "F#"],
    "E9sus4": ["E", "A", "B", "D", "F#"],
    "E13b5": ["E", "G#", "Bb", "D", "F#", "A", "C#"],
    "E13#5": ["E", "G#", "C", "D", "F#", "A", "C#"],
    "Esus2": ["E", "F#", "B"],
    "Esus4": ["E", "A", "B"],
    "E7sus2": ["E", "F#", "B", "D"],
    "E7sus4": ["E", "A", "B", "D"],
    "Em7sus2": ["E", "G", "B", "D"],
    "Em7sus4": ["E", "A", "B", "D"],
    "Emaj7sus2": ["E", "F#", "B", "D#"],
    "Emaj7sus4": ["E", "A", "B", "D#"],
    "Eadd9/F#": ["F#", "E", "G#", "B"],
    "Eadd9/G": ["G", "E", "G#", "B"],
    "Eadd9/A": ["A", "E", "G#", "B"],
    "Eadd9/B": ["B", "E", "G#", "B"],
    "Emaj7/F#": ["F#", "E", "G#", "B", "D#"],
    "Emaj7/G": ["G", "E", "G#", "B", "D#"],
    "Emaj7/A": ["A", "E", "G#", "B", "D#"],
    "Emaj7/B": ["B", "E", "G#", "B", "D#"],
    "E7/F#": ["F#", "E", "G#", "B", "D"],
    "E7/G": ["G", "E", "G#", "B", "D"],
    "E7/A": ["A", "E", "G#", "B", "D"],
    "E7/B": ["B", "E", "G#", "B", "D"],
    "Em7/F#": ["F#", "E", "G", "B", "D"],
    "Em7/G": ["G", "E", "G", "B", "D"],
    "Em7/A": ["A", "E", "G", "B", "D"],
    "Em7/B": ["B", "E", "G", "B", "D"],
    "Emaj9/F#": ["F#", "E", "G#", "B", "D#", "F#"],
    "Emaj9/G": ["G", "E", "G#", "B", "D#", "F#"],
    "Emaj9/A": ["A", "E", "G#", "B", "D#", "F#"],
    "Emaj9/B": ["B", "E", "G#", "B", "D#", "F#"],
    "E9/F#": ["F#", "E", "G#", "B", "D", "F#"],
    "E9/G": ["G", "E", "G#", "B", "D", "F#"],
    "E9/A": ["A", "E", "G#", "B", "D", "F#"],
    "E9/B": ["B", "E", "G#", "B", "D", "F#"],
    "Em9/F#": ["F#", "E", "G", "B", "D", "F#"],
    "Em9/G": ["G", "E", "G", "B", "D", "F#"],
    "Em9/A": ["A", "E", "G", "B", "D", "F#"],
    "Em9/B": ["B", "E", "G", "B", "D", "F#"],
    "Fb": ["Fb", "Ab", "Cb"],
    "Fbm": ["Fb", "G", "Cb"],
    "Fbdim": ["Fb", "G", "Bbb"],
    "Fbaug": ["Fb", "Ab", "C"],
    "Fbmaj7": ["Fb", "Ab", "Cb", "E"],
    "Fb7": ["Fb", "Ab", "Cb", "Db"],
    "Fbm7": ["Fb", "G", "Cb", "Db"],
    "Fbmaj9": ["Fb", "Ab", "Cb", "E", "G"],
    "Fb9": ["Fb", "Ab", "Cb", "Db", "G"],
    "Fbm9": ["Fb", "G", "Cb", "Db", "G"],
    "Fbmaj11": ["Fb", "Ab", "Cb", "E", "G", "Bb"],
    "Fb11": ["Fb", "Ab", "Cb", "Db", "G", "Bb"],
    "Fbm11": ["Fb", "G", "Cb", "Db", "G", "Bb"],
    "Fbmaj13": ["Fb", "Ab", "Cb", "E", "G", "Bb", "D"],
    "Fb13": ["Fb", "Ab", "Cb", "Db", "G", "Bb", "D"],
    "Fbm13": ["Fb", "G", "Cb", "Db", "G", "Bb", "D"],
    "Fbmaj6": ["Fb", "Ab", "Cb", "D"],
    "Fb6": ["Fb", "Ab", "Cb", "D"],
    "Fbm6": ["Fb", "G", "Cb", "D"],
    "Fbadd9": ["Fb", "Ab", "Cb", "G"],
    "Fbadd11": ["Fb", "Ab", "Cb", "D"],
    "Fbadd13": ["Fb", "Ab", "Cb", "E"],
    "Fbmadd9": ["Fb", "G", "Cb", "G"],
    "Fbmadd11": ["Fb", "G", "Cb", "D"],
    "Fbmadd13": ["Fb", "G", "Cb", "E"],
    "Fb6/9": ["Fb", "Ab", "Cb", "D", "G"],
    "Fbmaj7b5": ["Fb", "Ab", "C"],
    "Fbmaj7#5": ["Fb", "Ab", "C"],
    "Fbm7b5": ["Fb", "G", "Bbb"],
    "FbmMaj7": ["Fb", "G", "Cb", "E"],
    "Fb7b5": ["Fb", "Ab", "Bbb"],
    "Fb7#5": ["Fb", "Ab", "C"],
    "Fb7sus4": ["Fb", "A", "Cb", "Db"],
    "Fb9b5": ["Fb", "Ab", "Bbb", "Db", "G"],
    "Fb9#5": ["Fb", "Ab", "C", "Db", "G"],
    "Fb9sus4": ["Fb", "A", "Cb", "Db", "G"],
    "Fb13b5": ["Fb", "Ab", "Bbb", "Db", "G", "D"],
    "Fb13#5": ["Fb", "Ab", "C", "Db", "G", "D"],
    "Fbsus2": ["Fb", "Gb", "Cb"],
    "Fbsus4": ["Fb", "A", "Cb"],
    "Fb7sus2": ["Fb", "Gb", "Cb", "Db"],
    "Fb7sus4": ["Fb", "A", "Cb", "Db"],
    "Fbm7sus2": ["Fb", "G", "Cb", "Db"],
    "Fbm7sus4": ["Fb", "A", "Cb", "Db"],
    "Fbmaj7sus2": ["Fb", "Gb", "Cb", "E"],
    "Fbmaj7sus4": ["Fb", "A", "Cb", "E"],
    "Fbadd9/Ab": ["Ab", "Cb", "Fb"],
    "Fbadd9/A": ["A", "Cb", "Fb"],
    "Fbadd9/Db": ["Cb", "Fb"],
    "Fbadd9/E": ["Cb", "Fb", "Gb"],
    "Fbadd9/Ab": ["Ab", "Cb", "Fb"],
    "Fbmaj7/Ab": ["Ab", "Cb", "Fb", "E"],
    "Fbmaj7/A": ["A", "Cb", "Fb", "E"],
    "Fbmaj7/Db": ["Cb", "Fb", "E"],
    "Fbmaj7/E": ["Cb", "Fb", "E", "Gb"],
    "Fbmaj7/Ab": ["Ab", "Cb", "Fb", "E"],
    "Fb7/Ab": ["Ab", "Cb", "Fb", "Db"],
    "Fb7/A": ["A", "Cb", "Fb", "Db"],
    "Fb7/Db": ["Cb", "Fb", "Db"],
    "Fb7/E": ["Cb", "Fb", "Db", "Gb"],
    "Fb7/Ab": ["Ab", "Cb", "Fb", "Db"],
    "Fbm7/Ab": ["Ab", "Cb", "Fb", "Db"],
    "Fbm7/A": ["A", "Cb", "Fb", "Db"],
    "Fbm7/Db": ["Cb", "Fb", "Db"],
    "Fbm7/E": ["Cb", "Fb", "Db", "Gb"],
    "Fbm7/Ab": ["Ab", "Cb", "Fb", "Db"],
    "Fbmaj9/Ab": ["Ab", "Cb", "Fb", "E", "G"],
    "Fbmaj9/A": ["A", "Cb", "Fb", "E", "G"],
    "Fbmaj9/Db": ["Cb", "Fb", "E", "G"],
    "Fbmaj9/E": ["Cb", "Fb", "E", "Gb", "G"],
    "Fbmaj9/Ab": ["Ab", "Cb", "Fb", "E", "G"],
    "Fb9/Ab": ["Ab", "Cb", "Fb", "Db", "G"],
    "Fb9/A": ["A", "Cb", "Fb", "Db", "G"],
    "Fb9/Db": ["Cb", "Fb", "Db", "G"],
    "Fb9/E": ["Cb", "Fb", "Db", "Gb", "G"],
    "Fb9/Ab": ["Ab", "Cb", "Fb", "Db", "G"],
    "Fbm9/Ab": ["Ab", "Cb", "Fb", "Db", "G"],
    "Fbm9/A": ["A", "Cb", "Fb", "Db", "G"],
    "Fbm9/Db": ["Cb", "Fb", "Db", "G"],
    "Fbm9/E": ["Cb", "Fb", "Db", "Gb", "G"],
    "Fbm9/Ab": ["Ab", "Cb", "Fb", "Db", "G"],
    "F": ["F", "A", "C"],
    "Fm": ["F", "Ab", "C"],
    "Fdim": ["F", "Ab", "Cb"],
    "Faug": ["F", "A", "C#"],
    "Fmaj7": ["F", "A", "C", "E"],
    "F7": ["F", "A", "C", "Eb"],
    "Fm7": ["F", "Ab", "C", "Eb"],
    "Fmaj9": ["F", "A", "C", "E", "G"],
    "F9": ["F", "A", "C", "Eb", "G"],
    "Fm9": ["F", "Ab", "C", "Eb", "G"],
    "Fmaj11": ["F", "A", "C", "E", "G", "Bb"],
    "F11": ["F", "A", "C", "Eb", "G", "Bb"],
    "Fm11": ["F", "Ab", "C", "Eb", "G", "Bb"],
    "Fmaj13": ["F", "A", "C", "E", "G", "Bb", "D"],
    "F13": ["F", "A", "C", "Eb", "G", "Bb", "D"],
    "Fm13": ["F", "Ab", "C", "Eb", "G", "Bb", "D"],
    "Fmaj6": ["F", "A", "C", "D"],
    "F6": ["F", "A", "C", "D"],
    "Fm6": ["F", "Ab", "C", "D"],
    "Fadd9": ["F", "A", "C", "G"],
    "Fadd11": ["F", "A", "C", "Bb"],
    "Fadd13": ["F", "A", "C", "D"],
    "Fmadd9": ["F", "Ab", "C", "G"],
    "Fmadd11": ["F", "Ab", "C", "Bb"],
    "Fmadd13": ["F", "Ab", "C", "D"],
    "F6/9": ["F", "A", "C", "D", "G"],
    "Fmaj7b5": ["F", "A", "C#", "E"],
    "Fmaj7#5": ["F", "A", "C#", "E"],
    "Fm7b5": ["F", "Ab", "Cb", "Eb"],
    "FmMaj7": ["F", "Ab", "C", "E"],
    "F7b5": ["F", "A", "Cb", "Eb"],
    "F7#5": ["F", "A", "C#", "Eb"],
    "F7sus4": ["F", "Bb", "C", "Eb"],
    "F9b5": ["F", "A", "Cb", "Eb", "G"],
    "F9#5": ["F", "A", "C#", "Eb", "G"],
    "F9sus4": ["F", "Bb", "C", "Eb", "G"],
    "F13b5": ["F", "A", "Cb", "Eb", "G", "Bb", "D"],
    "F13#5": ["F", "A", "C#", "Eb", "G", "Bb", "D"],
    "Fsus2": ["F", "G", "C"],
    "Fsus4": ["F", "Bb", "C"],
    "F7sus2": ["F", "G", "C", "Eb"],
    "F7sus4": ["F", "Bb", "C", "Eb"],
    "Fm7sus2": ["F", "Ab", "C", "Eb"],
    "Fm7sus4": ["F", "Bb", "C", "Eb"],
    "Fmaj7sus2": ["F", "G", "C", "E"],
    "Fmaj7sus4": ["F", "Bb", "C", "E"],
    "Fadd9/G": ["G", "F", "A", "C"],
    "Fadd9/A": ["A", "F", "A", "C"],
    "Fadd9/Bb": ["Bb", "F", "A", "C"],
    "Fmaj7/G": ["G", "F", "A", "C", "E"],
    "Fmaj7/A": ["A", "F", "A", "C", "E"],
    "Fmaj7/Bb": ["Bb", "F", "A", "C", "E"],
    "F7/G": ["G", "F", "A", "C", "Eb"],
    "F7/A": ["A", "F", "A", "C", "Eb"],
    "F7/Bb": ["Bb", "F", "A", "C", "Eb"],
    "Fm7/G": ["G", "F", "Ab", "C", "Eb"],
    "Fm7/A": ["A", "F", "Ab", "C", "Eb"],
    "Fm7/Bb": ["Bb", "F", "Ab", "C", "Eb"],
    "Fmaj9/G": ["G", "F", "A", "C", "E", "G"],
    "Fmaj9/A": ["A", "F", "A", "C", "E", "G"],
    "Fmaj9/Bb": ["Bb", "F", "A", "C", "E", "G"],
    "F9/G": ["G", "F", "A", "C", "Eb", "G"],
    "F9/A": ["A", "F", "A", "C", "Eb", "G"],
    "F9/Bb": ["Bb", "F", "A", "C", "Eb", "G"],
    "Fm9/G": ["G", "F", "Ab", "C", "Eb", "G"],
    "Fm9/A": ["A", "F", "Ab", "C", "Eb", "G"],
    "Fm9/Bb": ["Bb", "F", "Ab", "C", "Eb", "G"],
    "F#": ["F#", "A#", "C#"],
    "F#m": ["F#", "A", "C#"],
    "F#dim": ["F#", "A", "C"],
    "F#aug": ["F#", "A#", "Cx"],
    "F#maj7": ["F#", "A#", "C#", "E#"],
    "F#7": ["F#", "A#", "C#", "E"],
    "F#m7": ["F#", "A", "C#", "E"],
    "F#maj9": ["F#", "A#", "C#", "E#", "G#"],
    "F#9": ["F#", "A#", "C#", "E", "G#"],
    "F#m9": ["F#", "A", "C#", "E", "G#"],
    "F#maj11": ["F#", "A#", "C#", "E#", "G#", "B"],
    "F#11": ["F#", "A#", "C#", "E", "G#", "B"],
    "F#m11": ["F#", "A", "C#", "E", "G#", "B"],
    "F#maj13": ["F#", "A#", "C#", "E#", "G#", "B", "D#"],
    "F#13": ["F#", "A#", "C#", "E", "G#", "B", "D#"],
    "F#m13": ["F#", "A", "C#", "E", "G#", "B", "D#"],
    "F#maj6": ["F#", "A#", "C#", "D#"],
    "F#6": ["F#", "A#", "C#", "D#"],
    "F#m6": ["F#", "A", "C#", "D#"],
    "F#add9": ["F#", "A#", "C#", "G#"],
    "F#add11": ["F#", "A#", "C#", "E"],
    "F#add13": ["F#", "A#", "C#", "D#"],
    "F#madd9": ["F#", "A", "C#", "G#"],
    "F#madd11": ["F#", "A", "C#", "E"],
    "F#madd13": ["F#", "A", "C#", "D#"],
    "F#6/9": ["F#", "A#", "C#", "D#", "G#"],
    "F#maj7b5": ["F#", "A#", "Cx"],
    "F#maj7#5": ["F#", "A#", "Cx"],
    "F#m7b5": ["F#", "A", "C"],
    "F#mMaj7": ["F#", "A", "C#", "E#"],
    "F#7b5": ["F#", "A#", "C"],
    "F#7#5": ["F#", "A#", "Cx"],
    "F#7sus4": ["F#", "B", "C#", "E"],
    "F#9b5": ["F#", "A#", "C", "E", "G#"],
    "F#9#5": ["F#", "A#", "Cx", "E", "G#"],
    "F#9sus4": ["F#", "B", "C#", "E", "G#"],
    "F#13b5": ["F#", "A#", "C", "E", "G#", "B", "D#"],
    "F#13#5": ["F#", "A#", "Cx", "E", "G#", "B", "D#"],
    "F#sus2": ["F#", "G#", "C#"],
    "F#sus4": ["F#", "B", "C#"],
    "F#7sus2": ["F#", "G#", "C#", "E"],
    "F#7sus4": ["F#", "B", "C#", "E"],
    "F#m7sus2": ["F#", "A", "C#", "E"],
    "F#m7sus4": ["F#", "B", "C#", "E"],
    "F#maj7sus2": ["F#", "G#", "C#", "E#"],
    "F#maj7sus4": ["F#", "B", "C#", "E#"],
    "F#add9/A#": ["A#", "F#", "A#", "C#", "E#"],
    "F#add9/B": ["B", "F#", "A#", "C#", "E#"],
    "F#maj7/A#": ["A#", "F#", "A#", "C#", "E#", "G#"],
    "F#maj7/B": ["B", "F#", "A#", "C#", "E#", "G#"],
    "F#7/A#": ["A#", "F#", "A#", "C#", "E"],
    "F#7/B": ["B", "F#", "A#", "C#", "E"],
    "F#m7/A#": ["A#", "F#", "A", "C#", "E"],
    "F#m7/B": ["B", "F#", "A", "C#", "E"],
    "F#maj9/A#": ["A#", "F#", "A#", "C#", "E#", "G#"],
    "F#maj9/B": ["B", "F#", "A#", "C#", "E#", "G#"],
    "F#9/A#": ["A#", "F#", "A#", "C#", "E", "G#"],
    "F#9/B": ["B", "F#", "A#", "C#", "E", "G#"],
    "F#m9/A#": ["A#", "F#", "A", "C#", "E", "G#"],
    "F#m9/B": ["B", "F#", "A", "C#", "E", "G#"],
    "Gb": ["Gb", "Bb", "Db"],
    "Gbm": ["Gb", "A", "Db"],
    "Gbdim": ["Gb", "A", "C"],
    "Gbaug": ["Gb", "Bb", "D"],
    "Gbmaj7": ["Gb", "Bb", "Db", "F"],
    "Gb7": ["Gb", "Bb", "Db", "E"],
    "Gbm7": ["Gb", "A", "Db", "E"],
    "Gbmaj9": ["Gb", "Bb", "Db", "F", "A"],
    "Gb9": ["Gb", "Bb", "Db", "E", "A"],
    "Gbm9": ["Gb", "A", "Db", "E", "A"],
    "Gbmaj11": ["Gb", "Bb", "Db", "F", "A", "C"],
    "Gb11": ["Gb", "Bb", "Db", "E", "A", "C"],
    "Gbm11": ["Gb", "A", "Db", "E", "A", "C"],
    "Gbmaj13": ["Gb", "Bb", "Db", "F", "A", "C", "Eb"],
    "Gb13": ["Gb", "Bb", "Db", "E", "A", "C", "Eb"],
    "Gbm13": ["Gb", "A", "Db", "E", "A", "C", "Eb"],
    "Gbmaj6": ["Gb", "Bb", "Db", "Eb"],
    "Gb6": ["Gb", "Bb", "Db", "Eb"],
    "Gbm6": ["Gb", "A", "Db", "Eb"],
    "Gbadd9": ["Gb", "Bb", "Db", "A"],
    "Gbadd11": ["Gb", "Bb", "Db", "Eb"],
    "Gbadd13": ["Gb", "Bb", "Db", "F"],
    "Gbmadd9": ["Gb", "A", "Db", "A"],
    "Gbmadd11": ["Gb", "A", "Db", "Eb"],
    "Gbmadd13": ["Gb", "A", "Db", "F"],
    "Gb6/9": ["Gb", "Bb", "Db", "Eb", "A"],
    "Gbmaj7b5": ["Gb", "Bb", "D"],
    "Gbmaj7#5": ["Gb", "Bb", "D"],
    "Gbm7b5": ["Gb", "A", "C"],
    "GbmMaj7": ["Gb", "A", "Db", "F"],
    "Gb7b5": ["Gb", "Bb", "C"],
    "Gb7#5": ["Gb", "Bb", "D"],
    "Gb7sus4": ["Gb", "B", "Db", "E"],
    "Gb9b5": ["Gb", "Bb", "C", "E", "A"],
    "Gb9#5": ["Gb", "Bb", "D", "E", "A"],
    "Gb9sus4": ["Gb", "B", "Db", "E", "A"],
    "Gb13b5": ["Gb", "Bb", "C", "E", "A", "Eb"],
    "Gb13#5": ["Gb", "Bb", "D", "E", "A", "Eb"],
    "Gbsus2": ["Gb", "Ab", "Db"],
    "Gbsus4": ["Gb", "B", "Db"],
    "Gb7sus2": ["Gb", "Ab", "Db", "E"],
    "Gb7sus4": ["Gb", "B", "Db", "E"],
    "Gbm7sus2": ["Gb", "A", "Db", "E"],
    "Gbm7sus4": ["Gb", "B", "Db", "E"],
    "Gbmaj7sus2": ["Gb", "Ab", "Db", "F"],
    "Gbmaj7sus4": ["Gb", "B", "Db", "F"],
    "Gbadd9/Ab": ["Ab", "Bb", "Db", "Gb"],
    "Gbadd9/B": ["B", "Db", "Gb", "Bb"],
    "Gbadd9/Db": ["Db", "Gb", "Bb"],
    "Gbadd9/Eb": ["Eb", "Gb", "Bb", "Db"],
    "Gbadd9/Ab": ["Ab", "Bb", "Db", "Gb"],
    "Gbmaj7/Ab": ["Ab", "Bb", "Db", "F", "Gb"],
    "Gbmaj7/B": ["B", "Db", "F", "Gb"],
    "Gbmaj7/Db": ["Db", "F", "Gb", "Bb"],
    "Gbmaj7/Eb": ["Eb", "Gb", "Bb", "Db", "F"],
    "Gbmaj7/Ab": ["Ab", "Bb", "Db", "F", "Gb"],
    "Gb7/Ab": ["Ab", "Bb", "Db", "E", "Gb"],
    "Gb7/B": ["B", "Db", "E", "Gb"],
    "Gb7/Db": ["Db", "E", "Gb", "Bb"],
    "Gb7/Eb": ["Eb", "Gb", "Bb", "Db", "E"],
    "Gb7/Ab": ["Ab", "Bb", "Db", "E", "Gb"],
    "Gbm7/Ab": ["Ab", "A", "Db", "E", "Gb"],
    "Gbm7/B": ["B", "Db", "E", "Gb"],
    "Gbm7/Db": ["Db", "E", "Gb", "A"],
    "Gbm7/Eb": ["Eb", "Gb", "A", "Db"],
    "Gbm7/Ab": ["Ab", "A", "Db", "E", "Gb"],
    "Gbmaj9/Ab": ["Ab", "Bb", "Db", "F", "Gb"],
    "Gbmaj9/B": ["B", "Db", "F", "Gb"],
    "Gbmaj9/Db": ["Db", "F", "Gb", "Bb"],
    "Gbmaj9/Eb": ["Eb", "Gb", "Bb", "Db", "F"],
    "Gbmaj9/Ab": ["Ab", "Bb", "Db", "F", "Gb"],
    "Gb9/Ab": ["Ab", "Bb", "Db", "E", "Gb"],
    "Gb9/B": ["B", "Db", "E", "Gb"],
    "Gb9/Db": ["Db", "E", "Gb", "Bb"],
    "Gb9/Eb": ["Eb", "Gb", "Bb", "Db", "E"],
    "Gb9/Ab": ["Ab", "Bb", "Db", "E", "Gb"],
    "Gbm9/Ab": ["Ab", "A", "Db", "E", "Gb"],
    "Gbm9/B": ["B", "Db", "E", "Gb"],
    "Gbm9/Db": ["Db", "E", "Gb", "A"],
    "Gbm9/Eb": ["Eb", "Gb", "A", "Db"],
    "Gbm9/Ab": ["Ab", "A", "Db", "E", "Gb"],
    "G": ["G", "B", "D"],
    "Gm": ["G", "Bb", "D"],
    "Gdim": ["G", "Bb", "Db"],
    "Gaug": ["G", "B", "D#"],
    "Gmaj7": ["G", "B", "D", "F#"],
    "G7": ["G", "B", "D", "F"],
    "Gm7": ["G", "Bb", "D", "F"],
    "Gmaj9": ["G", "B", "D", "F#", "A"],
    "G9": ["G", "B", "D", "F", "A"],
    "Gm9": ["G", "Bb", "D", "F", "A"],
    "Gmaj11": ["G", "B", "D", "F#", " A", "C"],
    "G11": ["G", "B", "D", "F", "A", "C"],
    "Gm11": ["G", "Bb", "D", "F", "A", "C"],
    "Gmaj13": ["G", "B", "D", "F#", "A", "C", "E"],
    "G13": ["G", "B", "D", "F", "A", "C", "E"],
    "Gm13": ["G", "Bb", "D", "F", "A", "C", "E"],
    "Gmaj6": ["G", "B", "D", "E"],
    "G6": ["G", "B", "D", "E"],
    "Gm6": ["G", "Bb", "D", "E"],
    "Gadd9": ["G", "B", "D", "A"],
    "Gadd11": ["G", "B", "D", "C"],
    "Gadd13": ["G", "B", "D", "E"],
    "Gmadd9": ["G", "Bb", "D", "A"],
    "Gmadd11": ["G", "Bb", "D", "C"],
    "Gmadd13": ["G", "Bb", "D", "E"],
    "G6/9": ["G", "B", "D", "E", "A"],
    "Gmaj7b5": ["G", "B", "D#", "F#"],
    "Gmaj7#5": ["G", "B", "D#", "F#"],
    "Gm7b5": ["G", "Bb", "Db", "F"],
    "GmMaj7": ["G", "Bb", "D", "F#"],
    "G7b5": ["G", "B", "Db", "F"],
    "G7#5": ["G", "B", "D#", "F"],
    "G7sus4": ["G", "C", "D", "F"],
    "G9b5": ["G", "B", "Db", "F", "A"],
    "G9#5": ["G", "B", "D#", "F", "A"],
    "G9sus4": ["G", "C", "D", "F", "A"],
    "G13b5": ["G", "B", "Db", "F", "A", "C", "E"],
    "G13#5": ["G", "B", "D#", "F", "A", "C", "E"],
    "Gsus2": ["G", "A", "D"],
    "Gsus4": ["G", "C", "D"],
    "G7sus2": ["G", "A", "D", "F"],
    "G7sus4": ["G", "C", "D", "F"],
    "Gm7sus2": ["G", "Bb", "D", "F"],
    "Gm7sus4": ["G", "C", "D", "F"],
    "Gmaj7sus2": ["G", "A", "D", "F#"],
    "Gmaj7sus4": ["G", "C", "D", "F#"],
    "Gadd9/A": ["A", "G", "B", "D"],
    "Gadd9/B": ["B", "G", "B", "D"],
    "Gadd9/C": ["C", "G", "B", "D"],
    "Gmaj7/A": ["A", "G", "B", "D", "F#"],
    "Gmaj7/B": ["B", "G", "B", "D", "F#"],
    "Gmaj7/C": ["C", "G", "B", "D", "F#"],
    "G7/A": ["A", "G", "B", "D", "F"],
    "G7/B": ["B", "G", "B", "D", "F"],
    "G7/C": ["C", "G", "B", "D", "F"],
    "Gm7/A": ["A", "G", "Bb", "D", "F"],
    "Gm7/B": ["B", "G", "Bb", "D", "F"],
    "Gm7/C": ["C", "G", "Bb", "D", "F"],
    "Gmaj9/A": ["A", "G", "B", "D", "F#", "A"],
    "Gmaj9/B": ["B", "G", "B", "D", "F#", "A"],
    "Gmaj9/C": ["C", "G", "B", "D", "F#", "A"],
    "G9/A": ["A", "G", "B", "D", "F", "A"],
    "G9/B": ["B", "G", "B", "D", "F", "A"],
    "G9/C": ["C", "G", "B", "D", "F", "A"],
    "Gm9/A": ["A", "G", "Bb", "D", "F", "A"],
    "Gm9/B": ["B", "G", "Bb", "D", "F", "A"],
    "Gm9/C": ["C", "G", "Bb", "D", "F", "A"],
    "G#": ["G#", "C", "D#"],
    "G#m": ["G#", "B", "D#"],
    "G#dim": ["G#", "B", "D"],
    "G#aug": ["G#", "C", "E"],
    "G#maj7": ["G#", "C", "D#", "G"],
    "G#7": ["G#", "C", "D#", "G"],
    "G#m7": ["G#", "B", "D#", "G#"],
    "G#maj9": ["G#", "C", "D#", "G", "A#"],
    "G#9": ["G#", "C", "D#", "G", "A#"],
    "G#m9": ["G#", "B", "D#", "G#", "A#"],
    "G#maj11": ["G#", "C", "D#", "G", "A#", "C#"],
    "G#11": ["G#", "C", "D#", "G", "A#", "C#"],
    "G#m11": ["G#", "B", "D#", "G#", "A#", "C#"],
    "G#maj13": ["G#", "C", "D#", "G", "A#", "C#", "E#"],
    "G#13": ["G#", "C", "D#", "G", "A#", "C#", "E#"],
    "G#m13": ["G#", "B", "D#", "G#", "A#", "C#", "E#"],
    "G#maj6": ["G#", "C", "D#", "E#"],
    "G#6": ["G#", "C", "D#", "E#"],
    "G#m6": ["G#", "B", "D#", "E#"],
    "G#add9": ["G#", "C", "D#", "A#"],
    "G#add11": ["G#", "C", "D#", "G"],
    "G#add13": ["G#", "C", "D#", "A#", "E#"],
    "G#madd9": ["G#", "B", "D#", "A#"],
    "G#madd11": ["G#", "B", "D#", "G"],
    "G#madd13": ["G#", "B", "D#", "A#", "E#"],
    "G#6/9": ["G#", "C", "D#", "E#", "A#"],
    "G#maj7b5": ["G#", "C", "E"],
    "G#maj7#5": ["G#", "C", "E#"],
    "G#m7b5": ["G#", "B", "D"],
    "G#mMaj7": ["G#", "B", "D#", "G#"],
    "G#7b5": ["G#", "C", "D"],
    "G#7#5": ["G#", "C", "D#", "E"],
    "G#7sus4": ["G#", "C#", "D#", "A#"],
    "G#9b5": ["G#", "C", "D", "G", "A#"],
    "G#9#5": ["G#", "C", "D#", "G", "A#"],
    "G#9sus4": ["G#", "C#", "D#", "G", "A#"],
    "G#13b5": ["G#", "C", "D", "G", "A#", "C#", "E#"],
    "G#13#5": ["G#", "C", "D#", "G", "A#", "C#", "E#"],
    "G#sus2": ["G#", "A#", "D#"],
    "G#sus4": ["G#", "C#", "D#"],
    "G#7sus2": ["G#", "A#", "D#", "G"],
    "G#7sus4": ["G#", "C#", "D#", "G"],
    "G#m7sus2": ["G#", "B", "D#", "G#"],
    "G#m7sus4": ["G#", "C#", "D#", "G#"],
    "G#maj7sus2": ["G#", "A#", "D#", "G#"],
    "G#maj7sus4": ["G#", "C#", "D#", "G#"],
    "G#add9/C": ["C", "G#", "C", "D#", "A#"],
    "G#add9/D": ["D", "G#", "C", "D#", "A#"],
    "G#add9/F": ["F", "G#", "C", "D#", "A#"],
    "G#add9/A#": ["A#", "G#", "C", "D#", "A#"],
    "G#add9/G": ["G", "G#", "C", "D#", "A#"],
    "G#maj7/C": ["C", "G#", "C", "D#", "G", "A#"],
    "G#maj7/D": ["D", "G#", "C", "D#", "G", "A#"],
    "G#maj7/F": ["F", "G#", "C", "D#", "G", "A#"],
    "G#maj7/A#": ["A#", "G#", "C", "D#", "G", "A#"],
    "G#maj7/G": ["G", "G#", "C", "D#", "G", "A#"],
    "G#7/C": ["C", "G#", "C", "D#", "G"],
    "G#7/D": ["D", "G#", "C", "D#", "G"],
    "G#7/F": ["F", "G#", "C", "D#", "G"],
    "G#7/A#": ["A#", "G#", "C", "D#", "G"],
    "G#7/G": ["G", "G#", "C", "D#", "G"],
    "G#m7/C": ["C", "G#", "B", "D#", "G#"],
    "G#m7/D": ["D", "G#", "B", "D#", "G#"],
    "G#m7/F": ["F", "G#", "B", "D#", "G#"],
    "G#m7/A#": ["A#", "G#", "B", "D#", "G#"],
    "G#m7/G": ["G", "G#", "B", "D#", "G#"],
    "G#maj9/C": ["C", "G#", "C", "D#", "G", "A#"],
    "G#maj9/D": ["D", "G#", "C", "D#", "G", "A#"],
    "G#maj9/F": ["F", "G#", "C", "D#", "G", "A#"],
    "G#maj9/A#": ["A#", "G#", "C", "D#", "G", "A#"],
    "G#maj9/G": ["G", "G#", "C", "D#", "G", "A#"],
    "G#9/C": ["C", "G#", "C", "D#", "G", "A#"],
    "G#9/D": ["D", "G#", "C", "D#", "G", "A#"],
    "G#9/F": ["F", "G#", "C", "D#", "G", "A#"],
    "G#9/A#": ["A#", "G#", "C", "D#", "G", "A#"],
    "G#9/G": ["G", "G#", "C", "D#", "G", "A#"],
    "G#m9/C": ["C", "G#", "B", "D#", "G#", "A#"],
    "G#m9/D": ["D", "G#", "B", "D#", "G#", "A#"],
    "G#m9/F": ["F", "G#", "B", "D#", "G#", "A#"],
    "G#m9/A#": ["A#", "G#", "B", "D#", "G#", "A#"],
    "G#m9/G": ["G", "G#", "B", "D#", "G#", "A#"],
    "Ab": ["Ab", "C", "Eb"],
    "Abm": ["Ab", "B", "Eb"],
    "Abdim": ["Ab", "B", "D"],
    "Abaug": ["Ab", "C", "E"],
    "Abmaj7": ["Ab", "C", "Eb", "G"],
    "Ab7": ["Ab", "C", "Eb", "Gb"],
    "Abm7": ["Ab", "B", "Eb", "Gb"],
    "Abmaj9": ["Ab", "C", "Eb", "G", "B"],
    "Ab9": ["Ab", "C", "Eb", "Gb", "B"],
    "Abm9": ["Ab", "B", "Eb", "Gb", "B"],
    "Abmaj11": ["Ab", "C", "Eb", "G", "B", "D"],
    "Ab11": ["Ab", "C", "Eb", "Gb", "B", "D"],
    "Abm11": ["Ab", "B", "Eb", "Gb", "B", "D"],
    "Abmaj13": ["Ab", "C", "Eb", "G", "B", "D", "F"],
    "Ab13": ["Ab", "C", "Eb", "Gb", "B", "D", "F"],
    "Abm13": ["Ab", "B", "Eb", "Gb", "B", "D", "F"],
    "Abmaj6": ["Ab", "C", "Eb", "F"],
    "Ab6": ["Ab", "C", "Eb", "F"],
    "Abm6": ["Ab", "B", "Eb", "F"],
    "Abadd9": ["Ab", "C", "Eb", "B"],
    "Abadd11": ["Ab", "C", "Eb", "F"],
    "Abadd13": ["Ab", "C", "Eb", "G"],
    "Abmadd9": ["Ab", "B", "Eb", "B"],
    "Abmadd11": ["Ab", "B", "Eb", "F"],
    "Abmadd13": ["Ab", "B", "Eb", "G"],
    "Ab6/9": ["Ab", "C", "Eb", "F", "B"],
    "Abmaj7b5": ["Ab", "C", "E"],
    "Abmaj7#5": ["Ab", "C", "E"],
    "Abm7b5": ["Ab", "B", "D"],
    "AbmMaj7": ["Ab", "B", "Eb", "G"],
    "Ab7b5": ["Ab", "C", "D"],
    "Ab7#5": ["Ab", "C", "E"],
    "Ab7sus4": ["Ab", "Db", "Eb", "Gb"],
    "Ab9b5": ["Ab", "C", "D", "Gb", "B"],
    "Ab9#5": ["Ab", "C", "E", "Gb", "B"],
    "Ab9sus4": ["Ab", "Db", "Eb", "Gb", "B"],
    "Ab13b5": ["Ab", "C", "D", "Gb", "B", "F"],
    "Ab13#5": ["Ab", "C", "E", "Gb", "B", "F"],
    "Absus2": ["Ab", "Bb", "Eb"],
    "Absus4": ["Ab", "Db", "Eb"],
    "Ab7sus2": ["Ab", "Bb", "Eb", "Gb"],
    "Ab7sus4": ["Ab", "Db", "Eb", "Gb"],
    "Abm7sus2": ["Ab", "B", "Eb", "Gb"],
    "Abm7sus4": ["Ab", "Db", "Eb", "Gb"],
    "Abmaj7sus2": ["Ab", "Bb", "Eb", "G"],
    "Abmaj7sus4": ["Ab", "Db", "Eb", "G"],
    "Abadd9/Bb": ["Bb", "C", "Eb", "Ab"],
    "Abadd9/Db": ["Db", "Eb", "Ab"],
    "Abadd9/Eb": ["Eb", "Ab", "C"],
    "Abadd9/F": ["F", "Ab", "C", "Eb"],
    "Abadd9/G": ["G", "Ab", "C", "Eb"],
    "Abadd9/Bb": ["Bb", "C", "Eb", "Ab"],
    "Abmaj7/Bb": ["Bb", "C", "Eb", "G", "Ab"],
    "Abmaj7/Db": ["Db", "Eb", "G", "Ab"],
    "Abmaj7/Eb": ["Eb", "Ab", "C", "G"],
    "Abmaj7/F": ["F", "Ab", "C", "Eb", "G"],
    "Abmaj7/G": ["G", "Ab", "C", "Eb", "B"],
    "Abmaj7/Bb": ["Bb", "C", "Eb", "G", "Ab"],
    "Ab7/Bb": ["Bb", "C", "Eb", "Gb", "Ab"],
    "Ab7/Db": ["Db", "Eb", "Gb", "Ab"],
    "Ab7/Eb": ["Eb", "Ab", "C", "Gb"],
    "Ab7/F": ["F", "Ab", "C", "Eb", "Gb"],
    "Ab7/G": ["G", "Ab", "C", "Eb", "Bbb"],
    "Ab7/Bb": ["Bb", "C", "Eb", "Gb", "Ab"],
    "Abm7/Bb": ["Bb", "B", "Eb", "Gb", "Ab"],
    "Abm7/Db": ["Db", "Eb", "Gb", "Ab"],
    "Abm7/Eb": ["Eb", "Ab", "B", "Gb"],
    "Abm7/F": ["F", "Ab", "B", "Eb", "Gb"],
    "Abm7/G": ["G", "Ab", "B", "Eb", "Db"],
    "Abm7/Bb": ["Bb", "B", "Eb", "Gb", "Ab"],
    "Abmaj9/Bb": ["Bb", "C", "Eb", "G", "Ab"],
    "Abmaj9/Db": ["Db", "Eb", "G", "Ab"],
    "Abmaj9/Eb": ["Eb", "Ab", "C", "G", "B"],
    "Abmaj9/F": ["F", "Ab", "C", "Eb", "G"],
    "Abmaj9/G": ["G", "Ab", "C", "Eb", "B", "D"],
    "Abmaj9/Bb": ["Bb", "C", "Eb", "G", "Ab"],
    "Ab9/Bb": ["Bb", "C", "Eb", "Gb", "Ab"],
    "Ab9/Db": ["Db", "Eb", "Gb", "Ab"],
    "Ab9/Eb": ["Eb", "Ab", "C", "Gb", "B"],
    "Ab9/F": ["F", "Ab", "C", "Eb", "Gb"],
    "Ab9/G": ["G", "Ab", "C", "Eb", "B", "D"],
    "Ab9/Bb": ["Bb", "C", "Eb", "Gb", "Ab"],
    "Abm9/Bb": ["Bb", "B", "Eb", "Gb", "Ab"],
    "Abm9/Db": ["Db", "Eb", "Gb", "Ab"],
    "Abm9/Eb": ["Eb", "Ab", "B", "Gb", "B"],
    "Abm9/F": ["F", "Ab", "B", "Eb", "Gb"],
    "Abm9/G": ["G", "Ab", "B", "Eb", "Db"],
    "Abm9/Bb": ["Bb", "B", "Eb", "Gb", "Ab"],
    "A": ["A", "C#", "E"],
    "Am": ["A", "C", "E"],
    "Adim": ["A", "C", "Eb"],
    "Aaug": ["A", "C#", "E#"],
    "Amaj7": ["A", "C#", "E", "G#"],
    "A7": ["A", "C#", "E", "G"],
    "Am7": ["A", "C", "E", "G"],
    "Amaj9": ["A", "C#", "E", "G#", "B"],
    "A9": ["A", "C#", "E", "G", "B"],
    "Am9": ["A", "C", "E", "G", "B"],
    "Amaj11": ["A", "C#", "E", "G#", "B", "D"],
    "A11": ["A", "C#", "E", "G", "B", "D"],
    "Am11": ["A", "C", "E", "G", "B", "D"],
    "Amaj13": ["A", "C#", "E", "G#", "B", "D", "F#"],
    "A13": ["A", "C#", "E", "G", "B", "D", "F#"],
    "Am13": ["A", "C", "E", "G", "B", "D", "F#"],
    "Amaj6": ["A", "C#", "E", "F#"],
    "A6": ["A", "C#", "E", "F#"],
    "Am6": ["A", "C", "E", "F#"],
    "Aadd9": ["A", "C#", "E", "B"],
    "Aadd11": ["A", "C#", "E", "D"],
    "Aadd13": ["A", "C#", "E", "F#"],
    "Amadd9": ["A", "C", "E", "B"],
    "Amadd11": ["A", "C", "E", "D"],
    "Amadd13": ["A", "C", "E", "F#"],
    "A6/9": ["A", "C#", "E", "F#", "B"],
    "Amaj7b5": ["A", "C#", "Eb", "G#"],
    "Amaj7#5": ["A", "C#", "E#", "G#"],
    "Am7b5": ["A", "C", "Eb", "G"],
    "AmMaj7": ["A", "C", "E", "G#"],
    "A7b5": ["A", "C#", "Eb", "G"],
    "A7#5": ["A", "C#", "E#", "G"],
    "A7sus4": ["A", "D", "E", "G"],
    "A9b5": ["A", "C#", "Eb", "G", "B"],
    "A9#5": ["A", "C#", "E#", "G", "B"],
    "A9sus4": ["A", "D", "E", "G", "B"],
    "A13b5": ["A", "C#", "Eb", "G", "B", "D", "F#"],
    "A13#5": ["A", "C#", "E#", "G", "B", "D", "F#"],
    "Asus2": ["A", "B", "E"],
    "Asus4": ["A", "D", "E"],
    "A7sus2": ["A", "B", "E", "G"],
    "A7sus4": ["A", "D", "E", "G"],
    "Am7sus2": ["A", "C", "E", "G"],
    "Am7sus4": ["A", "D", "E", "G"],
    "Amaj7sus2": ["A", "B", "E", "G#"],
    "Amaj7sus4": ["A", "D", "E", "G#"],
    "Aadd9/B": ["B", "A", "C#", "E"],
    "Aadd9/D": ["D", "A", "C#", "E"],
    "Aadd9/E": ["E", "A", "C#", "E"],
    "Amaj7/B": ["B", "A", "C#", "E", "G#"],
    "Amaj7/D": ["D", "A", "C#", "E", "G#"],
    "Amaj7/E": ["E", "A", "C#", "E", "G#"],
    "A7/B": ["B", "A", "C#", "E", "G"],
    "A7/D": ["D", "A", "C#", "E", "G"],
    "A7/E": ["E", "A", "C#", "E", "G"],
    "Am7/B": ["B", "A", "C", "E", "G"],
    "Am7/D": ["D", "A", "C", "E", "G"],
    "Am7/E": ["E", "A", "C", "E", "G"],
    "Amaj9/B": ["B", "A", "C#", "E", "G#", "B"],
    "Amaj9/D": ["D", "A", "C#", "E", "G#", "B"],
    "Amaj9/E": ["E", "A", "C#", "E", "G#", "B"],
    "A9/B": ["B", "A", "C#", "E", "G", "B"],
    "A9/D": ["D", "A", "C#", "E", "G", "B"],
    "A9/E": ["E", "A", "C#", "E", "G", "B"],
    "Am9/B": ["B", "A", "C", "E", "G", "B"],
    "Am9/D": ["D", "A", "C", "E", "G", "B"],
    "Am9/E": ["E", "A", "C", "E", "G", "B"],
    "A#": ["A#", "D", "F"],
    "A#m": ["A#", "C#", "F"],
    "A#dim": ["A#", "C#", "E"],
    "A#aug": ["A#", "D", "Fx"],
    "A#maj7": ["A#", "D", "F", "A"],
    "A#7": ["A#", "D", "F", "G#"],
    "A#m7": ["A#", "C#", "F", "G#"],
    "A#maj9": ["A#", "D", "F", "A", "C#"],
    "A#9": ["A#", "D", "F", "G#", "C#"],
    "A#m9": ["A#", "C#", "F", "G#", "C#"],
    "A#maj11": ["A#", "D", "F", "A", "C#", "E"],
    "A#11": ["A#", "D", "F", "G#", "C#", "E"],
    "A#m11": ["A#", "C#", "F", "G#", "C#", "E"],
    "A#maj13": ["A#", "D", "F", "A", "C#", "E", "G#"],
    "A#13": ["A#", "D", "F", "G#", "C#", "E", "G#"],
    "A#m13": ["A#", "C#", "F", "G#", "C#", "E", "G#"],
    "A#maj6": ["A#", "D", "F", "G"],
    "A#6": ["A#", "D", "F", "G"],
    "A#m6": ["A#", "C#", "F", "G"],
    "A#add9": ["A#", "D", "F", "G#", "C"],
    "A#add11": ["A#", "D", "F", "A"],
    "A#add13": ["A#", "D", "F", "G#", "C", "E"],
    "A#madd9": ["A#", "C#", "F", "G#", "D"],
    "A#madd11": ["A#", "C#", "F", "A"],
    "A#madd13": ["A#", "C#", "F", "G#", "D", "E"],
    "A#6/9": ["A#", "D", "F", "G", "C", "D"],
    "A#maj7b5": ["A#", "D", "G#"],
    "A#maj7#5": ["A#", "D", "Gx"],
    "A#m7b5": ["A#", "C#", "E"],
    "A#mMaj7": ["A#", "C#", "F", "A"],
    "A#7b5": ["A#", "D", "E"],
    "A#7#5": ["A#", "D", "G#"],
    "A#7sus4": ["A#", "D#", "F", "G#"],
    "A#9b5": ["A#", "D", "E", "G#", "C#"],
    "A#9#5": ["A#", "D", "Gx", "G#", "C#"],
    "A#9sus4": ["A#", "D#", "F", "G#", "C#"],
    "A#13b5": ["A#", "D", "E", "G#", "C#", "E", "G#"],
    "A#13#5": ["A#", "D", "Gx", "G#", "C#", "E", "G#"],
    "A#sus2": ["A#", "B", "F"],
    "A#sus4": ["A#", "D#", "F"],
    "A#7sus2": ["A#", "B", "F", "G#"],
    "A#7sus4": ["A#", "D#", "F", "G#"],
    "A#m7sus2": ["A#", "C#", "F", "G#"],
    "A#m7sus4": ["A#", "D#", "F", "G#"],
    "A#maj7sus2": ["A#", "B", "F", "A"],
    "A#maj7sus4": ["A#", "D#", "F", "A"],
    "A#add9/C": ["C", "A#", "D", "F", "G#"],
    "A#add9/D": ["D", "A#", "D", "F", "G#"],
    "A#add9/F": ["F", "A#", "D", "F", "G#"],
    "A#add9/G": ["G", "A#", "D", "F", "G#"],
    "A#maj7/C": ["C", "A#", "D", "F", "A"],
    "A#maj7/D": ["D", "A#", "D", "F", "A"],
    "A#maj7/F": ["F", "A#", "D", "F", "A"],
    "A#maj7/G": ["G", "A#", "D", "F", "A"],
    "A#7/C": ["C", "A#", "D", "F", "G#"],
    "A#7/D": ["D", "A#", "D", "F", "G#"],
    "A#7/F": ["F", "A#", "D", "F", "G#"],
    "A#7/G": ["G", "A#", "D", "F", "G#"],
    "A#m7/C": ["C", "A#", "C#", "F", "G#"],
    "A#m7/D": ["D", "A#", "C#", "F", "G#"],
    "A#m7/F": ["F", "A#", "C#", "F", "G#"],
    "A#m7/G": ["G", "A#", "C#", "F", "G#"],
    "A#maj9/C": ["C", "A#", "D", "F", "A", "C#"],
    "A#maj9/D": ["D", "A#", "D", "F", "A", "C#"],
    "A#maj9/F": ["F", "A#", "D", "F", "A", "C#"],
    "A#maj9/G": ["G", "A#", "D", "F", "A", "C#"],
    "A#9/C": ["C", "A#", "D", "F", "G#", "C#"],
    "A#9/D": ["D", "A#", "D", "F", "G#", "C#"],
    "A#9/F": ["F", "A#", "D", "F", "G#", "C#"],
    "A#9/G": ["G", "A#", "D", "F", "G#", "C#"],
    "A#m9/C": ["C", "A#", "C#", "F", "G#", "C#"],
    "A#m9/D": ["D", "A#", "C#", "F", "G#", "C#"],
    "A#m9/F": ["F", "A#", "C#", "F", "G#", "C#"],
    "A#m9/G": ["G", "A#", "C#", "F", "G#", "C#"],
    "Bb": ["Bb", "D", "F"],
    "Bbm": ["Bb", "Db", "F"],
    "Bbdim": ["Bb", "Db", "E"],
    "Bbaug": ["Bb", "D", "F#"],
    "Bbmaj7": ["Bb", "D", "F", "A"],
    "Bb7": ["Bb", "D", "F", "Ab"],
    "Bbm7": ["Bb", "Db", "F", "Ab"],
    "Bbmaj9": ["Bb", "D", "F", "A", "C"],
    "Bb9": ["Bb", "D", "F", "Ab", "C"],
    "Bbm9": ["Bb", "Db", "F", "Ab", "C"],
    "Bbmaj11": ["Bb", "D", "F", "A", "C", "Eb"],
    "Bb11": ["Bb", "D", "F", "Ab", "C", "Eb"],
    "Bbm11": ["Bb", "Db", "F", "Ab", "C", "Eb"],
    "Bbmaj13": ["Bb", "D", "F", "A", "C", "Eb", "G"],
    "Bb13": ["Bb", "D", "F", "Ab", "C", "Eb", "G"],
    "Bbm13": ["Bb", "Db", "F", "Ab", "C", "Eb", "G"],
    "Bbmaj6": ["Bb", "D", "F", "G"],
    "Bb6": ["Bb", "D", "F", "G"],
    "Bbm6": ["Bb", "Db", "F", "G"],
    "Bbadd9": ["Bb", "D", "F", "C"],
    "Bbadd11": ["Bb", "D", "F", "G"],
    "Bbadd13": ["Bb", "D", "F", "A"],
    "Bbmadd9": ["Bb", "Db", "F", "C"],
    "Bbmadd11": ["Bb", "Db", "F", "G"],
    "Bbmadd13": ["Bb", "Db", "F", "A"],
    "Bb6/9": ["Bb", "D", "F", "G", "C"],
    "Bbmaj7b5": ["Bb", "D", "F#"],
    "Bbmaj7#5": ["Bb", "D", "F#"],
    "Bbm7b5": ["Bb", "Db", "E"],
    "BbmMaj7": ["Bb", "Db", "F", "A"],
    "Bb7b5": ["Bb", "D", "E"],
    "Bb7#5": ["Bb", "D", "F#"],
    "Bb7sus4": ["Bb", "Eb", "F", "Ab"],
    "Bb9b5": ["Bb", "D", "E", "Ab", "C"],
    "Bb9#5": ["Bb", "D", "F#", "Ab", "C"],
    "Bb9sus4": ["Bb", "Eb", "F", "Ab", "C"],
    "Bb13b5": ["Bb", "D", "E", "Ab", "C", "G"],
    "Bb13#5": ["Bb", "D", "F#", "Ab", "C", "G"],
    "Bbsus2": ["Bb", "C", "F"],
    "Bbsus4": ["Bb", "Eb", "F"],
    "Bb7sus2": ["Bb", "C", "F", "Ab"],
    "Bb7sus4": ["Bb", "Eb", "F", "Ab"],
    "Bbm7sus2": ["Bb", "Db", "F", "Ab"],
    "Bbm7sus4": ["Bb", "Eb", "F", "Ab"],
    "Bbmaj7sus2": ["Bb", "C", "F", "A"],
    "Bbmaj7sus4": ["Bb", "Eb", "F", "A"],
    "Bbadd9/C": ["C", "D", "F", "Bb"],
    "Bbadd9/D": ["D", "F", "Bb"],
    "Bbadd9/E": ["E", "F", "Bb"],
    "Bbadd9/F": ["F", "Bb", "D"],
    "Bbadd9/G": ["G", "Bb", "D", "F"],
    "Bbadd9/A": ["A", "Bb", "D", "F"],
    "Bbmaj7/C": ["C", "D", "F", "A", "Bb"],
    "Bbmaj7/D": ["D", "F", "A", "Bb"],
    "Bbmaj7/E": ["E", "F", "A", "Bb"],
    "Bbmaj7/F": ["F", "A", "Bb", "D"],
    "Bbmaj7/G": ["G", "Bb", "D", "A"],
    "Bbmaj7/A": ["A", "Bb", "D", "F", "C"],
    "Bb7/C": ["C", "D", "F", "Ab", "Bb"],
    "Bb7/D": ["D", "F", "Ab", "Bb"],
    "Bb7/E": ["E", "F", "Ab", "Bb"],
    "Bb7/F": ["F", "Ab", "Bb", "D"],
    "Bb7/G": ["G", "Bb", "D", "Ab"],
    "Bb7/A": ["A", "Bb", "D", "F", "Eb"],
    "Bbm7/C": ["C", "Db", "F", "Ab", "Bb"],
    "Bbm7/D": ["D", "F", "Ab", "Bb"],
    "Bbm7/E": ["E", "F", "Ab", "Bb"],
    "Bbm7/F": ["F", "Ab", "Bb", "Db"],
    "Bbm7/G": ["G", "Ab", "Bb", "Db"],
    "Bbm7/A": ["A", "Bb", "Db", "F", "C"],
    "Bbmaj9/C": ["C", "D", "F", "A", "Bb"],
    "Bbmaj9/D": ["D", "F", "A", "Bb"],
    "Bbmaj9/E": ["E", "F", "A", "Bb"],
    "Bbmaj9/F": ["F", "A", "Bb", "D"],
    "Bbmaj9/G": ["G", "Bb", "D", "A"],
    "Bbmaj9/A": ["A", "Bb", "D", "F", "C"],
    "Bb9/C": ["C", "D", "F", "Ab", "Bb"],
    "Bb9/D": ["D", "F", "Ab", "Bb"],
    "Bb9/E": ["E", "F", "Ab", "Bb"],
    "Bb9/F": ["F", "Ab", "Bb", "D"],
    "Bb9/G": ["G", "Bb", "D", "Ab"],
    "Bb9/A": ["A", "Bb", "D", "F", "Eb"],
    "Bbm9/C": ["C", "Db", "F", "Ab", "Bb"],
    "Bbm9/D": ["D", "F", "Ab", "Bb"],
    "Bbm9/E": ["E", "F", "Ab", "Bb"],
    "Bbm9/F": ["F", "Ab", "Bb", "Db"],
    "Bbm9/G": ["G", "Ab", "Bb", "Db"],
    "Bbm9/A": ["A", "Bb", "Db", "F", "C"],
    "B": ["B", "D#", "F#"],
    "Bm": ["B", "D", "F#"],
    "Bdim": ["B", "D", "F"],
    "Baug": ["B", "D#", "G"],
    "Bmaj7": ["B", "D#", "F#", "A#"],
    "B7": ["B", "D#", "F#", "A"],
    "Bm7": ["B", "D", "F#", "A"],
    "Bmaj9": ["B", "D#", "F#", "A#", "C#"],
    "B9": ["B", "D#", "F#", "A", "C#"],
    "Bm9": ["B", "D", "F#", "A", "C#"],
    "Bmaj11": ["B", "D#", "F#", "A#", "C#", "E"],
    "B11": ["B", "D#", "F#", "A", "C#", "E"],
    "Bm11": ["B", "D", "F#", "A", "C#", "E"],
    "Bmaj13": ["B", "D#", "F#", "A#", "C#", "E", "G#"],
    "B13": ["B", "D#", "F#", "A", "C#", "E", "G#"],
    "Bm13": ["B", "D", "F#", "A", "C#", "E", "G#"],
    "Bmaj6": ["B", "D#", "F#", "G#"],
    "B6": ["B", "D#", "F#", "G#"],
    "Bm6": ["B", "D", "F#", "G#"],
    "Badd9": ["B", "D#", "F#", "C#"],
    "Badd11": ["B", "D#", "F#", "E"],
    "Badd13": ["B", "D#", "F#", "G#"],
    "Bmadd9": ["B", "D", "F#", "C#"],
    "Bmadd11": ["B", "D", "F#", "E"],
    "Bmadd13": ["B", "D", "F#", "G#"],
    "B6/9": ["B", "D#", "F#", "G#", "C#"],
    "Bmaj7b5": ["B", "D#", "F", "A#"],
    "Bmaj7#5": ["B", "D#", "G", "A#"],
    "Bm7b5": ["B", "D", "F", "A"],
    "BmMaj7": ["B", "D", "F#", "A#"],
    "B7b5": ["B", "D#", "F", "A"],
    "B7#5": ["B", "D#", "G", "A"],
    "B7sus4": ["B", "E", "F#", "A"],
    "B9b5": ["B", "D#", "F", "A", "C#"],
    "B9#5": ["B", "D#", "G", "A", "C#"],
    "B9sus4": ["B", "E", "F#", "A", "C#"],
    "B13b5": ["B", "D#", "F", "A", "C#", "E", "G#"],
    "B13#5": ["B", "D#", "G", "A", "C#", "E", "G#"],
    "Bsus2": ["B", "C#", "F#"],
    "Bsus4": ["B", "E", "F#"],
    "B7sus2": ["B", "C#", "F#", "A"],
    "B7sus4": ["B", "E", "F#", "A"],
    "Bm7sus2": ["B", "D", "F#", "A"],
    "Bm7sus4": ["B", "E", "F#", "A"],
    "Bmaj7sus2": ["B", "C#", "F#", "A#"],
    "Bmaj7sus4": ["B", "E", "F#", "A#"],
    "Badd9/C#": ["C#", "B", "D#", "F#"],
    "Badd9/D#": ["D#", "B", "D#", "F#"],
    "Badd9/F#": ["F#", "B", "D#", "F#"],
    "Bmaj7/C#": ["C#", "B", "D#", "F#", "A#"],
    "Bmaj7/D#": ["D#", "B", "D#", "F#", "A#"],
    "Bmaj7/F#": ["F#", "B", "D#", "F#", "A#"],
    "B7/C#": ["C#", "B", "D#", "F#", "A"],
    "B7/D#": ["D#", "B", "D#", "F#", "A"],
    "B7/F#": ["F#", "B", "D#", "F#", "A"],
    "Bm7/C#": ["C#", "B", "D", "F#", "A"],
    "Bm7/D#": ["D#", "B", "D", "F#", "A"],
    "Bm7/F#": ["F#", "B", "D", "F#", "A"],
    "Bmaj9/C#": ["C#", "B", "D#", "F#", "A#", "C#"],
    "Bmaj9/D#": ["D#", "B", "D#", "F#", "A#", "C#"],
    "Bmaj9/F#": ["F#", "B", "D#", "F#", "A#", "C#"],
    "B9/C#": ["C#", "B", "D#", "F#", "A", "C#"],
    "B9/D#": ["D#", "B", "D#", "F#", "A", "C#"],
    "B9/F#": ["F#", "B", "D#", "F#", "A", "C#"],
    "Bm9/C#": ["C#", "B", "D", "F#", "A", "C#"],
    "Bm9/D#": ["D#", "B", "D", "F#", "A", "C#"],
    "Bm9/F#": ["F#", "B", "D", "F#", "A", "C#"],
    "Cb": ["Cb", "Ebb", "Abb"],
    "Cbm": ["Cb", "Db", "Abb"],
    "Cbdim": ["Cb", "Db", "E"],
    "Cbaug": ["Cb", "Ebb", "A"],
    "Cbmaj7": ["Cb", "Ebb", "Abb", "Bb"],
    "Cb7": ["Cb", "Ebb", "Abb", "Bbb"],
    "Cbm7": ["Cb", "Db", "Abb", "Bb"],
    "Cbmaj9": ["Cb", "Ebb", "Abb", "Bb", "Db"],
    "Cb9": ["Cb", "Ebb", "Abb", "Bbb", "Db"],
    "Cbm9": ["Cb", "Db", "Abb", "Bb", "Db"],
    "Cbmaj11": ["Cb", "Ebb", "Abb", "Bb", "Db", "Fb"],
    "Cb11": ["Cb", "Ebb", "Abb", "Bbb", "Db", "Fb"],
    "Cbm11": ["Cb", "Db", "Abb", "Bb", "Db", "Fb"],
    "Cbmaj13": ["Cb", "Ebb", "Abb", "Bb", "Db", "Fb", "Ab"],
    "Cb13": ["Cb", "Ebb", "Abb", "Bbb", "Db", "Fb", "Ab"],
    "Cbm13": ["Cb", "Db", "Abb", "Bb", "Db", "Fb", "Ab"],
    "Cbmaj6": ["Cb", "Ebb", "Abb", "B"],
    "Cb6": ["Cb", "Ebb", "Abb", "B"],
    "Cbm6": ["Cb", "Db", "Abb", "B"],
    "Cbadd9": ["Cb", "Ebb", "Abb", "Db"],
    "Cbadd11": ["Cb", "Ebb", "Abb", "Fb"],
    "Cbadd13": ["Cb", "Ebb", "Abb", "Ab"],
    "Cbmadd9": ["Cb", "Db", "Abb", "Db"],
    "Cbmadd11": ["Cb", "Db", "Abb", "Fb"],
    "Cbmadd13": ["Cb", "Db", "Abb", "Ab"],
    "Cb6/9": ["Cb", "Ebb", "Abb", "B", "Db"],
    "Cbmaj7b5": ["Cb", "Ebb", "A"],
    "Cbmaj7#5": ["Cb", "Ebb", "A"],
    "Cbm7b5": ["Cb", "Db", "E"],
    "CbmMaj7": ["Cb", "Db", "Abb", "Bb"],
    "Cb7b5": ["Cb", "Ebb", "E"],
    "Cb7#5": ["Cb", "Ebb", "A"],
    "Cb7sus4": ["Cb", "Fb", "Abb", "Bbb"],
    "Cb9b5": ["Cb", "Ebb", "E", "Bbb", "Db"],
    "Cb9#5": ["Cb", "Ebb", "A", "Bbb", "Db"],
    "Cb9sus4": ["Cb", "Fb", "Abb", "Bbb", "Db"],
    "Cb13b5": ["Cb", "Ebb", "E", "Bbb", "Db", "Ab"],
    "Cb13#5": ["Cb", "Ebb", "A", "Bbb", "Db", "Ab"],
    "Cbsus2": ["Cb", "Db", "Abb"],
    "Cbsus4": ["Cb", "Fb", "Abb"],
    "Cb7sus2": ["Cb", "Db", "Abb", "Bbb"],
    "Cb7sus4": ["Cb", "Fb", "Abb", "Bbb"],
    "Cbm7sus2": ["Cb", "Db", "Abb", "Bb"],
    "Cbm7sus4": ["Cb", "Fb", "Abb", "Bb"],
    "Cbmaj7sus2": ["Cb", "Db", "Abb", "B"],
    "Cbmaj7sus4": ["Cb", "Fb", "Abb", "B"],
    "Cbadd9/Db": ["Db", "Ebb", "Abb", "Cb"],
    "Cbadd9/Eb": ["Eb", "Abb", "Cb"],
    "Cbadd9/F": ["F", "Abb", "Cb"],
    "Cbadd9/Gb": ["Gb", "Cb", "Ebb"],
    "Cbadd9/Ab": ["Ab", "Cb", "Ebb", "Abb"],
    "Cbadd9/Bb": ["Bb", "Cb", "Ebb", "Abb"],
    "Cbmaj7/Db": ["Db", "Ebb", "Abb", "Bb", "Cb"],
    "Cbmaj7/Eb": ["Eb", "Abb", "Bb", "Cb"],
    "Cbmaj7/F": ["F", "Abb", "Bb", "Cb"],
    "Cbmaj7/Gb": ["Gb", "Cb", "Ebb", "Bb"],
    "Cbmaj7/Ab": ["Ab", "Cb", "Ebb", "Abb", "Bb"],
    "Cbmaj7/Bb": ["Bb", "Cb", "Ebb", "Abb", "Bb"],
    "Cb7/Db": ["Db", "Ebb", "Abb", "Bbb", "Cb"],
    "Cb7/Eb": ["Eb", "Abb", "Bbb", "Cb"],
    "Cb7/F": ["F", "Abb", "Bbb", "Cb"],
    "Cb7/Gb": ["Gb", "Bbb", "Cb", "Ebb"],
    "Cb7/Ab": ["Ab", "Cb", "Ebb", "Abb", "Bbb"],
    "Cb7/Bb": ["Bb", "Cb", "Ebb", "Abb", "Bbb"],
    "Cbm7/Db": ["Db", "D", "Abb", "Bb", "Cb"],
    "Cbm7/Eb": ["Eb", "Abb", "Bb", "Cb"],
    "Cbm7/F": ["F", "Abb", "Bb", "Cb"],
    "Cbm7/Gb": ["Gb", "Bb", "Cb", "D"],
    "Cbm7/Ab": ["Ab", "A", "Cb", "D", "Abb"],
    "Cbm7/Bb": ["Bb", "Cb", "D", "Abb", "A"],
    "Cbmaj9/Db": ["Db", "Ebb", "Abb", "Bb", "Cb"],
    "Cbmaj9/Eb": ["Eb", "Abb", "Bb", "Cb"],
    "Cbmaj9/F": ["F", "Abb", "Bb", "Cb"],
    "Cbmaj9/Gb": ["Gb", "Cb", "Ebb", "Bb", "Db"],
    "Cbmaj9/Ab": ["Ab", "Cb", "Ebb", "Abb", "Bb", "Db"],
    "Cbmaj9/Bb": ["Bb", "Cb", "Ebb", "Abb", "Bb", "Db"],
    "Cb9/Db": ["Db", "Ebb", "Abb", "Bbb", "Cb"],
    "Cb9/Eb": ["Eb", "Abb", "Bbb", "Cb"],
    "Cb9/F": ["F", "Abb", "Bbb", "Cb"],
    "Cb9/Gb": ["Gb", "Bbb", "Cb", "Ebb", "Db"],
    "Cb9/Ab": ["Ab", "Cb", "Ebb", "Abb", "Bbb", "Db"],
    "Cb9/Bb": ["Bb", "Cb", "Ebb", "Abb", "Bbb", "Db"],
    "Cbm9/Db": ["Db", "D", "Abb", "Bb", "Cb"],
    "Cbm9/Eb": ["Eb", "Abb", "Bb", "Cb"],
    "Cbm9/F": ["F", "Abb", "Bb", "Cb"],
    "Cbm9/Gb": ["Gb", "Bb", "Cb", "D", "D"],
    "Cbm9/Ab": ["Ab", "A", "Cb", "D", "Abb"],
    "Cbm9/Bb": ["Bb", "Cb", "D", "Abb", "A"],
}