# Generated by Django 4.2.4 on 2023-08-28 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_remove_auctionlisting_end_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="auction_listing",
            new_name="listing",
        ),
    ]
